# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.srcs/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdmi_tx_bd_vid_phy_controller_0_0.xci
# IP: The module: 'hdmi_tx_bd_vid_phy_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper || ORIG_REF_NAME==hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper} -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/synth/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper_ooc.xdc

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/synth/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper || ORIG_REF_NAME==hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdmi_tx_bd_vid_phy_controller_0_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdmi_tx_bd_vid_phy_controller_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdmi_tx_bd_vid_phy_controller_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.srcs/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdmi_tx_bd_vid_phy_controller_0_0.xci
# IP: The module: 'hdmi_tx_bd_vid_phy_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper || ORIG_REF_NAME==hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper} -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/synth/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper_ooc.xdc

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/synth/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper || ORIG_REF_NAME==hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/vid_phy_controller_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdmi_tx_bd_vid_phy_controller_0_0_ooc_fixed.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdmi_tx_bd_vid_phy_controller_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdmi_tx_bd_vid_phy_controller_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_vid_phy_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
