-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hdmi_tx_bd_v_tpg_0_0_tpgForeground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    bckgndYUV_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    bckgndYUV_empty_n : IN STD_LOGIC;
    bckgndYUV_read : OUT STD_LOGIC;
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    height_val : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val : IN STD_LOGIC_VECTOR (15 downto 0);
    patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
    maskId_val : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val : IN STD_LOGIC_VECTOR (7 downto 0);
    crossHairX_val : IN STD_LOGIC_VECTOR (15 downto 0);
    crossHairY_val : IN STD_LOGIC_VECTOR (15 downto 0);
    boxSize_val : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorR_val : IN STD_LOGIC_VECTOR (7 downto 0);
    boxColorG_val : IN STD_LOGIC_VECTOR (7 downto 0);
    boxColorB_val : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val : IN STD_LOGIC_VECTOR (7 downto 0);
    ovrlayYUV_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    ovrlayYUV_full_n : IN STD_LOGIC;
    ovrlayYUV_write : OUT STD_LOGIC;
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of hdmi_tx_bd_v_tpg_0_0_tpgForeground is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_F0 : STD_LOGIC_VECTOR (7 downto 0) := "11110000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal whiYuv_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal whiYuv_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal boxHCoord : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal boxVCoord : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal colorFormat_val_read_reg_418 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal icmp_ln1947_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1947_reg_429 : STD_LOGIC_VECTOR (0 downto 0);
    signal motionSpeed_val_read_reg_434 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal boxColorB_val_read_reg_439 : STD_LOGIC_VECTOR (7 downto 0);
    signal boxColorG_val_read_reg_444 : STD_LOGIC_VECTOR (7 downto 0);
    signal boxColorR_val_read_reg_449 : STD_LOGIC_VECTOR (7 downto 0);
    signal boxSize_val_read_reg_454 : STD_LOGIC_VECTOR (15 downto 0);
    signal crossHairY_val_read_reg_459 : STD_LOGIC_VECTOR (15 downto 0);
    signal crossHairX_val_read_reg_464 : STD_LOGIC_VECTOR (15 downto 0);
    signal maskId_val_read_reg_470 : STD_LOGIC_VECTOR (7 downto 0);
    signal patternId_val_read_reg_475 : STD_LOGIC_VECTOR (7 downto 0);
    signal width_val_read_reg_480 : STD_LOGIC_VECTOR (15 downto 0);
    signal height_val_read_reg_485 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1977_fu_300_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1977_reg_490 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln1989_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1989_reg_495 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1991_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1991_reg_500 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1993_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1993_reg_505 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1881_fu_346_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1881_reg_510 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1882_fu_352_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1882_reg_515 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1947_fu_358_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1947_reg_520 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_365_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln_reg_525 : STD_LOGIC_VECTOR (8 downto 0);
    signal whiYuv_2_load_reg_530 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_1_reg_535 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln1963_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1963_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_start : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_done : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_idle : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_ready : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_bckgndYUV_read : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ovrlayYUV_din : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ovrlayYUV_write : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord_ap_vld : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord_ap_vld : STD_LOGIC;
    signal grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln772_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal boxHCoord_loc_0_fu_112 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal boxVCoord_loc_0_fu_108 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln1975_fu_247_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_fu_104 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y_2_fu_382_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal whiYuv_2_ce0_local : STD_LOGIC;
    signal icmp_ln1975_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_256_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1974_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1989_fu_308_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_318_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_332_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hdmi_tx_bd_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bckgndYUV_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        bckgndYUV_empty_n : IN STD_LOGIC;
        bckgndYUV_read : OUT STD_LOGIC;
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        ovrlayYUV_full_n : IN STD_LOGIC;
        ovrlayYUV_write : OUT STD_LOGIC;
        ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        colorFormat_val : IN STD_LOGIC_VECTOR (7 downto 0);
        shl_ln : IN STD_LOGIC_VECTOR (8 downto 0);
        maskId_val : IN STD_LOGIC_VECTOR (7 downto 0);
        width_val : IN STD_LOGIC_VECTOR (15 downto 0);
        select_ln1977 : IN STD_LOGIC_VECTOR (7 downto 0);
        and_ln1989 : IN STD_LOGIC_VECTOR (0 downto 0);
        and_ln1993 : IN STD_LOGIC_VECTOR (0 downto 0);
        and_ln1991 : IN STD_LOGIC_VECTOR (0 downto 0);
        patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
        boxSize_val : IN STD_LOGIC_VECTOR (15 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        boxColorB_val : IN STD_LOGIC_VECTOR (7 downto 0);
        boxColorG_val : IN STD_LOGIC_VECTOR (7 downto 0);
        boxColorR_val : IN STD_LOGIC_VECTOR (7 downto 0);
        pixOut_17 : IN STD_LOGIC_VECTOR (7 downto 0);
        vMax : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln789 : IN STD_LOGIC_VECTOR (7 downto 0);
        hMax : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln1977 : IN STD_LOGIC_VECTOR (15 downto 0);
        icmp_ln1963 : IN STD_LOGIC_VECTOR (0 downto 0);
        crossHairX_val : IN STD_LOGIC_VECTOR (15 downto 0);
        whiYuv_2_load : IN STD_LOGIC_VECTOR (7 downto 0);
        boxHCoord_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        boxHCoord_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxHCoord_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        boxVCoord_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        boxVCoord_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxVCoord_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        boxVCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxVCoord_ap_vld : OUT STD_LOGIC;
        boxHCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxHCoord_ap_vld : OUT STD_LOGIC );
    end component;


    component hdmi_tx_bd_v_tpg_0_0_tpgForeground_whiYuv_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    whiYuv_2_U : component hdmi_tx_bd_v_tpg_0_0_tpgForeground_whiYuv_2_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => whiYuv_2_address0,
        ce0 => whiYuv_2_ce0_local,
        q0 => whiYuv_2_q0);

    grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201 : component hdmi_tx_bd_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_start,
        ap_done => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_done,
        ap_idle => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_idle,
        ap_ready => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_ready,
        bckgndYUV_dout => bckgndYUV_dout,
        bckgndYUV_empty_n => bckgndYUV_empty_n,
        bckgndYUV_read => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_bckgndYUV_read,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        ovrlayYUV_din => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ovrlayYUV_din,
        ovrlayYUV_full_n => ovrlayYUV_full_n,
        ovrlayYUV_write => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ovrlayYUV_write,
        ovrlayYUV_num_data_valid => ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap => ovrlayYUV_fifo_cap,
        colorFormat_val => colorFormat_val_read_reg_418,
        shl_ln => shl_ln_reg_525,
        maskId_val => maskId_val_read_reg_470,
        width_val => width_val_read_reg_480,
        select_ln1977 => select_ln1977_reg_490,
        and_ln1989 => and_ln1989_reg_495,
        and_ln1993 => and_ln1993_reg_505,
        and_ln1991 => and_ln1991_reg_500,
        patternId_val => patternId_val_read_reg_475,
        boxSize_val => boxSize_val_read_reg_454,
        y => y_1_reg_535,
        boxColorB_val => boxColorB_val_read_reg_439,
        boxColorG_val => boxColorG_val_read_reg_444,
        boxColorR_val => boxColorR_val_read_reg_449,
        pixOut_17 => select_ln1947_reg_520,
        vMax => sub_ln1882_reg_515,
        zext_ln789 => motionSpeed_val_read_reg_434,
        hMax => sub_ln1881_reg_510,
        zext_ln1977 => crossHairX_val_read_reg_464,
        icmp_ln1963 => icmp_ln1963_reg_543,
        crossHairX_val => crossHairX_val_read_reg_464,
        whiYuv_2_load => whiYuv_2_load_reg_530,
        boxHCoord_loc_1_out_i => boxHCoord_loc_0_fu_112,
        boxHCoord_loc_1_out_o => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord_loc_1_out_o,
        boxHCoord_loc_1_out_o_ap_vld => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord_loc_1_out_o_ap_vld,
        boxVCoord_loc_1_out_i => boxVCoord_loc_0_fu_108,
        boxVCoord_loc_1_out_o => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord_loc_1_out_o,
        boxVCoord_loc_1_out_o_ap_vld => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord_loc_1_out_o_ap_vld,
        boxVCoord => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord,
        boxVCoord_ap_vld => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord_ap_vld,
        boxHCoord => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord,
        boxHCoord_ap_vld => grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln772_fu_377_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln772_fu_377_p2 = ap_const_lv1_0))) then 
                    grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_ready = ap_const_logic_1)) then 
                    grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    boxHCoord_loc_0_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                boxHCoord_loc_0_fu_112 <= boxHCoord;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord_loc_1_out_o_ap_vld = ap_const_logic_1))) then 
                boxHCoord_loc_0_fu_112 <= grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord_loc_1_out_o;
            end if; 
        end if;
    end process;

    boxVCoord_loc_0_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                boxVCoord_loc_0_fu_108 <= boxVCoord;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord_loc_1_out_o_ap_vld = ap_const_logic_1))) then 
                boxVCoord_loc_0_fu_108 <= grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord_loc_1_out_o;
            end if; 
        end if;
    end process;

    y_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_104 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln772_fu_377_p2 = ap_const_lv1_0))) then 
                y_fu_104 <= y_2_fu_382_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                and_ln1989_reg_495 <= and_ln1989_fu_312_p2;
                and_ln1991_reg_500 <= and_ln1991_fu_326_p2;
                and_ln1993_reg_505 <= and_ln1993_fu_340_p2;
                boxColorB_val_read_reg_439 <= boxColorB_val;
                boxColorG_val_read_reg_444 <= boxColorG_val;
                boxColorR_val_read_reg_449 <= boxColorR_val;
                boxSize_val_read_reg_454 <= boxSize_val;
                crossHairX_val_read_reg_464 <= crossHairX_val;
                crossHairY_val_read_reg_459 <= crossHairY_val;
                height_val_read_reg_485 <= height_val;
                maskId_val_read_reg_470 <= maskId_val;
                motionSpeed_val_read_reg_434 <= motionSpeed_val;
                patternId_val_read_reg_475 <= patternId_val;
                select_ln1947_reg_520 <= select_ln1947_fu_358_p3;
                    select_ln1977_reg_490(6 downto 4) <= select_ln1977_fu_300_p3(6 downto 4);
                    shl_ln_reg_525(8 downto 1) <= shl_ln_fu_365_p3(8 downto 1);
                sub_ln1881_reg_510 <= sub_ln1881_fu_346_p2;
                sub_ln1882_reg_515 <= sub_ln1882_fu_352_p2;
                whiYuv_2_load_reg_530 <= whiYuv_2_q0;
                width_val_read_reg_480 <= width_val;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord_ap_vld = ap_const_logic_1))) then
                boxHCoord <= grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxHCoord;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord_ap_vld = ap_const_logic_1))) then
                boxVCoord <= grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_boxVCoord;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                colorFormat_val_read_reg_418 <= colorFormat_val;
                icmp_ln1947_reg_429 <= icmp_ln1947_fu_266_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                icmp_ln1963_reg_543 <= icmp_ln1963_fu_388_p2;
                y_1_reg_535 <= y_fu_104;
            end if;
        end if;
    end process;
    select_ln1977_reg_490(3 downto 0) <= "0000";
    select_ln1977_reg_490(7) <= '1';
    shl_ln_reg_525(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state3, grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_done, icmp_ln772_fu_377_p2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln772_fu_377_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    and_ln1989_fu_312_p2 <= (trunc_ln1989_fu_308_p1 and icmp_ln1974_fu_295_p2);
    and_ln1991_fu_326_p2 <= (tmp_fu_318_p3 and icmp_ln1974_fu_295_p2);
    and_ln1993_fu_340_p2 <= (tmp_2_fu_332_p3 and icmp_ln1974_fu_295_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_done)
    begin
        if ((grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln772_fu_377_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln772_fu_377_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    bckgndYUV_read <= grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_bckgndYUV_read;
    grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_start <= grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ap_start_reg;
    icmp_ln1947_fu_266_p2 <= "0" when (tmp_3_fu_256_p4 = ap_const_lv7_0) else "1";
    icmp_ln1963_fu_388_p2 <= "1" when (y_fu_104 = crossHairY_val_read_reg_459) else "0";
    icmp_ln1974_fu_295_p2 <= "1" when (colorFormat_val_read_reg_418 = ap_const_lv8_0) else "0";
    icmp_ln1975_fu_241_p2 <= "1" when (colorFormat_val = ap_const_lv8_1) else "0";
    icmp_ln772_fu_377_p2 <= "1" when (y_fu_104 = height_val_read_reg_485) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln772_fu_377_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln772_fu_377_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ovrlayYUV_din <= grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ovrlayYUV_din;
    ovrlayYUV_write <= grp_tpgForeground_Pipeline_VITIS_LOOP_774_2_fu_201_ovrlayYUV_write;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln1947_fu_358_p3 <= 
        boxColorB_val when (icmp_ln1947_reg_429(0) = '1') else 
        boxColorG_val;
    select_ln1975_fu_247_p3 <= 
        ap_const_lv64_1 when (icmp_ln1975_fu_241_p2(0) = '1') else 
        ap_const_lv64_2;
    select_ln1977_fu_300_p3 <= 
        ap_const_lv8_F0 when (icmp_ln1974_fu_295_p2(0) = '1') else 
        ap_const_lv8_80;
    shl_ln_fu_365_p3 <= (motionSpeed_val & ap_const_lv1_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln1881_fu_346_p2 <= std_logic_vector(unsigned(width_val) - unsigned(boxSize_val));
    sub_ln1882_fu_352_p2 <= std_logic_vector(unsigned(height_val) - unsigned(boxSize_val));
    tmp_2_fu_332_p3 <= maskId_val(2 downto 2);
    tmp_3_fu_256_p4 <= colorFormat_val(7 downto 1);
    tmp_fu_318_p3 <= maskId_val(1 downto 1);
    trunc_ln1989_fu_308_p1 <= maskId_val(1 - 1 downto 0);
    whiYuv_2_address0 <= select_ln1975_fu_247_p3(2 - 1 downto 0);

    whiYuv_2_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            whiYuv_2_ce0_local <= ap_const_logic_1;
        else 
            whiYuv_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    y_2_fu_382_p2 <= std_logic_vector(unsigned(y_fu_104) + unsigned(ap_const_lv16_1));
end behav;
