-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hdmi_tx_bd_v_tpg_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_video_TVALID : IN STD_LOGIC;
    srcYUV_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    srcYUV_full_n : IN STD_LOGIC;
    srcYUV_write : OUT STD_LOGIC;
    srcYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    srcYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    p_4_0_0_0186422_lcssa447_i : IN STD_LOGIC_VECTOR (0 downto 0);
    p_0_0_0_0178415_lcssa431_i : IN STD_LOGIC_VECTOR (47 downto 0);
    sof_4_i : IN STD_LOGIC_VECTOR (0 downto 0);
    colorFormat_val27 : IN STD_LOGIC_VECTOR (7 downto 0);
    trunc_ln_i : IN STD_LOGIC_VECTOR (9 downto 0);
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
    s_axis_video_TREADY : OUT STD_LOGIC;
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    p_4_0_0_0186423_i_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_4_0_0_0186423_i_out_ap_vld : OUT STD_LOGIC;
    p_0_0_0_0178414_i_out : OUT STD_LOGIC_VECTOR (47 downto 0);
    p_0_0_0_0178414_i_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of hdmi_tx_bd_v_tpg_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln850_reg_451 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln854_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op42_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln850_reg_451_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln850_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal srcYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal s_axis_video_TDATA_blk_n : STD_LOGIC;
    signal eol_reg_191 : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_reg_202 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal colorFormat_val27_read_reg_433 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln880_fu_213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln880_reg_444 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_phi_mux_eol_phi_fu_195_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_phi_mux_sof_phi_fu_206_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_110 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal j_4_fu_243_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_j_3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0178414_i_fu_114 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal p_4_0_0_0186423_i_fu_118 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_2_i_fu_284_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln63_fu_292_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_i_fu_303_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_fu_341_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_i_fu_325_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_fu_341_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_i_fu_333_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_fu_341_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln880_1_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_i_fu_356_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_198_fu_377_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_369_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_fu_341_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln880_2_fu_318_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln880_1_fu_311_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln880_fu_296_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_355 : BOOLEAN;
    signal tmp_i_fu_341_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_fu_341_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (7 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (7 downto 0);
        din1_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component hdmi_tx_bd_v_tpg_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_5_8_8_1_1_U12 : component hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000000",
        din0_WIDTH => 8,
        CASE1 => "00000001",
        din1_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 8,
        dout_WIDTH => 8)
    port map (
        din0 => tmp_i_fu_341_p2,
        din1 => tmp_i_fu_341_p4,
        def => tmp_i_fu_341_p5,
        sel => colorFormat_val27_read_reg_433,
        dout => tmp_i_fu_341_p7);

    flow_control_loop_pipe_sequential_init_U : component hdmi_tx_bd_v_tpg_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    eol_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln850_reg_451_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                eol_reg_191 <= p_4_0_0_0186423_i_fu_118;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                eol_reg_191 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    j_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln850_fu_237_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_110 <= j_4_fu_243_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_110 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    p_0_0_0_0178414_i_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    p_0_0_0_0178414_i_fu_114 <= p_0_0_0_0178415_lcssa431_i;
                elsif ((ap_const_boolean_1 = ap_condition_355)) then 
                    p_0_0_0_0178414_i_fu_114 <= s_axis_video_TDATA;
                end if;
            end if; 
        end if;
    end process;

    p_4_0_0_0186423_i_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    p_4_0_0_0186423_i_fu_118 <= p_4_0_0_0186422_lcssa447_i;
                elsif ((ap_const_boolean_1 = ap_condition_355)) then 
                    p_4_0_0_0186423_i_fu_118 <= s_axis_video_TLAST;
                end if;
            end if; 
        end if;
    end process;

    sof_reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln850_reg_451_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                sof_reg_202 <= ap_const_lv1_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                sof_reg_202 <= sof_4_i;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                colorFormat_val27_read_reg_433 <= colorFormat_val27;
                icmp_ln850_reg_451 <= icmp_ln850_fu_237_p2;
                icmp_ln850_reg_451_pp0_iter1_reg <= icmp_ln850_reg_451;
                icmp_ln880_reg_444 <= icmp_ln880_fu_213_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(s_axis_video_TVALID, ap_predicate_op42_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op42_read_state2 = ap_const_boolean_1) and (s_axis_video_TVALID = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(srcYUV_full_n, icmp_ln850_reg_451_pp0_iter1_reg)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln850_reg_451_pp0_iter1_reg = ap_const_lv1_0) and (srcYUV_full_n = ap_const_logic_0));
    end process;


    ap_condition_355_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln850_reg_451, or_ln854_fu_254_p2)
    begin
                ap_condition_355 <= ((or_ln854_fu_254_p2 = ap_const_lv1_0) and (icmp_ln850_reg_451 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln850_fu_237_p2)
    begin
        if (((icmp_ln850_fu_237_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln850_reg_451, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln850_reg_451 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_eol_phi_fu_195_p4_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln850_reg_451_pp0_iter1_reg, ap_block_pp0_stage0, eol_reg_191, p_4_0_0_0186423_i_fu_118)
    begin
        if (((icmp_ln850_reg_451_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_phi_mux_eol_phi_fu_195_p4 <= p_4_0_0_0186423_i_fu_118;
        else 
            ap_phi_mux_eol_phi_fu_195_p4 <= eol_reg_191;
        end if; 
    end process;


    ap_phi_mux_sof_phi_fu_206_p4_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln850_reg_451_pp0_iter1_reg, ap_block_pp0_stage0, sof_reg_202)
    begin
        if (((icmp_ln850_reg_451_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_phi_mux_sof_phi_fu_206_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_sof_phi_fu_206_p4 <= sof_reg_202;
        end if; 
    end process;


    ap_predicate_op42_read_state2_assign_proc : process(icmp_ln850_reg_451, or_ln854_fu_254_p2)
    begin
                ap_predicate_op42_read_state2 <= ((or_ln854_fu_254_p2 = ap_const_lv1_0) and (icmp_ln850_reg_451 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_110)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_3 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_j_3 <= j_fu_110;
        end if; 
    end process;

    empty_198_fu_377_p3 <= 
        tmp_5_i_fu_325_p3 when (icmp_ln880_1_fu_364_p2(0) = '1') else 
        tmp_7_i_fu_356_p3;
    empty_fu_369_p3 <= 
        tmp_7_i_fu_356_p3 when (icmp_ln880_1_fu_364_p2(0) = '1') else 
        tmp_6_i_fu_333_p3;
    icmp_ln850_fu_237_p2 <= "1" when (ap_sig_allocacmp_j_3 = trunc_ln_i) else "0";
    icmp_ln880_1_fu_364_p2 <= "1" when (colorFormat_val27_read_reg_433 = ap_const_lv8_1) else "0";
    icmp_ln880_fu_213_p2 <= "1" when (colorFormat_val27 = ap_const_lv8_0) else "0";
    j_4_fu_243_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_3) + unsigned(ap_const_lv10_1));
    or_ln854_fu_254_p2 <= (ap_phi_mux_sof_phi_fu_206_p4 or ap_phi_mux_eol_phi_fu_195_p4);
    p_0_0_0_0178414_i_out <= p_0_0_0_0178414_i_fu_114;

    p_0_0_0_0178414_i_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln850_reg_451, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln850_reg_451 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            p_0_0_0_0178414_i_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_0_0_0178414_i_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_4_0_0_0186423_i_out <= p_4_0_0_0186423_i_fu_118;

    p_4_0_0_0186423_i_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln850_reg_451, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln850_reg_451 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            p_4_0_0_0186423_i_out_ap_vld <= ap_const_logic_1;
        else 
            p_4_0_0_0186423_i_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_video_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, s_axis_video_TVALID, ap_predicate_op42_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op42_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_video_TDATA_blk_n <= s_axis_video_TVALID;
        else 
            s_axis_video_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_video_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op42_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op42_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_video_TREADY <= ap_const_logic_1;
        else 
            s_axis_video_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    select_ln880_1_fu_311_p3 <= 
        trunc_ln63_fu_292_p1 when (icmp_ln880_reg_444(0) = '1') else 
        tmp_4_i_fu_303_p3;
    select_ln880_2_fu_318_p3 <= 
        tmp_4_i_fu_303_p3 when (icmp_ln880_reg_444(0) = '1') else 
        tmp_2_i_fu_284_p3;
    select_ln880_fu_296_p3 <= 
        tmp_2_i_fu_284_p3 when (icmp_ln880_reg_444(0) = '1') else 
        trunc_ln63_fu_292_p1;

    srcYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, srcYUV_full_n, icmp_ln850_reg_451_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((icmp_ln850_reg_451_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            srcYUV_blk_n <= srcYUV_full_n;
        else 
            srcYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    srcYUV_din <= (((((empty_198_fu_377_p3 & empty_fu_369_p3) & tmp_i_fu_341_p7) & select_ln880_2_fu_318_p3) & select_ln880_1_fu_311_p3) & select_ln880_fu_296_p3);

    srcYUV_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln850_reg_451_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln850_reg_451_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            srcYUV_write <= ap_const_logic_1;
        else 
            srcYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_2_i_fu_284_p3 <= p_0_0_0_0178414_i_fu_114(23 downto 16);
    tmp_4_i_fu_303_p3 <= p_0_0_0_0178414_i_fu_114(15 downto 8);
    tmp_5_i_fu_325_p3 <= p_0_0_0_0178414_i_fu_114(47 downto 40);
    tmp_6_i_fu_333_p3 <= p_0_0_0_0178414_i_fu_114(31 downto 24);
    tmp_7_i_fu_356_p3 <= p_0_0_0_0178414_i_fu_114(39 downto 32);
    tmp_i_fu_341_p2 <= p_0_0_0_0178414_i_fu_114(47 downto 40);
    tmp_i_fu_341_p4 <= p_0_0_0_0178414_i_fu_114(31 downto 24);
    tmp_i_fu_341_p5 <= p_0_0_0_0178414_i_fu_114(23 downto 16);
    trunc_ln63_fu_292_p1 <= p_0_0_0_0178414_i_fu_114(8 - 1 downto 0);
end behav;
