# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/HDMI_Pass_Thru_ExDes/v_hdmi_rx_ss_0_ex/imports/hdmi_example_aup.xdc

# Block Designs: bd/exdes/exdes.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes || ORIG_REF_NAME==exdes} -quiet] -quiet

# IP: bd/exdes/ip/exdes_axi_gpio_0/exdes_axi_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_axi_gpio_0 || ORIG_REF_NAME==exdes_axi_gpio_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_v_tpg_0/exdes_v_tpg_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_v_tpg_0 || ORIG_REF_NAME==exdes_v_tpg_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_aud_pat_gen_0/exdes_aud_pat_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_aud_pat_gen_0 || ORIG_REF_NAME==exdes_aud_pat_gen_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_xbar_4/exdes_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_xbar_4 || ORIG_REF_NAME==exdes_xbar_4} -quiet] -quiet

# IP: bd/exdes/ip/exdes_axi_interconnect_0/exdes_axi_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_axi_interconnect_0 || ORIG_REF_NAME==exdes_axi_interconnect_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_clk_wiz_0 || ORIG_REF_NAME==exdes_clk_wiz_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_hdmi_acr_ctrl_0/exdes_hdmi_acr_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_hdmi_acr_ctrl_0 || ORIG_REF_NAME==exdes_hdmi_acr_ctrl_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_axi_intc_0/exdes_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_axi_intc_0 || ORIG_REF_NAME==exdes_axi_intc_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_xbar_5/exdes_xbar_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_xbar_5 || ORIG_REF_NAME==exdes_xbar_5} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_cc_0/exdes_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_auto_cc_0 || ORIG_REF_NAME==exdes_auto_cc_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_cc_1/exdes_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_auto_cc_1 || ORIG_REF_NAME==exdes_auto_cc_1} -quiet] -quiet

# IP: bd/exdes/ip/exdes_axi_interconnect_1/exdes_axi_interconnect_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_axi_interconnect_1 || ORIG_REF_NAME==exdes_axi_interconnect_1} -quiet] -quiet

# IP: bd/exdes/ip/exdes_axi_uartlite_0/exdes_axi_uartlite_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_axi_uartlite_0 || ORIG_REF_NAME==exdes_axi_uartlite_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_clk_wiz_1/exdes_clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_clk_wiz_1 || ORIG_REF_NAME==exdes_clk_wiz_1} -quiet] -quiet

# IP: bd/exdes/ip/exdes_dlmb_bram_if_cntlr_0/exdes_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==exdes_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_dlmb_v10_0/exdes_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_dlmb_v10_0 || ORIG_REF_NAME==exdes_dlmb_v10_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_fmch_axi_iic_0/exdes_fmch_axi_iic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_fmch_axi_iic_0 || ORIG_REF_NAME==exdes_fmch_axi_iic_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_ilmb_bram_if_cntlr_0/exdes_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==exdes_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_ilmb_v10_0/exdes_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_ilmb_v10_0 || ORIG_REF_NAME==exdes_ilmb_v10_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_lmb_bram_0/exdes_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_lmb_bram_0 || ORIG_REF_NAME==exdes_lmb_bram_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_mblaze_0/exdes_mblaze_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_mblaze_0 || ORIG_REF_NAME==exdes_mblaze_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_mdm_0/exdes_mdm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_mdm_0 || ORIG_REF_NAME==exdes_mdm_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_rst_processor_1_100M_0/exdes_rst_processor_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_rst_processor_1_100M_0 || ORIG_REF_NAME==exdes_rst_processor_1_100M_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_rst_processor_1_300M_0 || ORIG_REF_NAME==exdes_rst_processor_1_300M_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_xlconcat_0/exdes_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_xlconcat_0 || ORIG_REF_NAME==exdes_xlconcat_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_fmch_axi_iic_1/exdes_fmch_axi_iic_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_fmch_axi_iic_1 || ORIG_REF_NAME==exdes_fmch_axi_iic_1} -quiet] -quiet

# IP: bd/exdes/ip/exdes_rx_video_axis_reg_slice_0/exdes_rx_video_axis_reg_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_rx_video_axis_reg_slice_0 || ORIG_REF_NAME==exdes_rx_video_axis_reg_slice_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_tx_video_axis_reg_slice_0/exdes_tx_video_axis_reg_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_tx_video_axis_reg_slice_0 || ORIG_REF_NAME==exdes_tx_video_axis_reg_slice_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_v_hdmi_rx_ss_0/exdes_v_hdmi_rx_ss_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_v_hdmi_rx_ss_0 || ORIG_REF_NAME==exdes_v_hdmi_rx_ss_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_v_hdmi_tx_ss_0/exdes_v_hdmi_tx_ss_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_v_hdmi_tx_ss_0 || ORIG_REF_NAME==exdes_v_hdmi_tx_ss_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_vcc_const_0/exdes_vcc_const_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_vcc_const_0 || ORIG_REF_NAME==exdes_vcc_const_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_vid_phy_controller_0/exdes_vid_phy_controller_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exdes_vid_phy_controller_0 || ORIG_REF_NAME==exdes_vid_phy_controller_0} -quiet] -quiet

# XDC: /home/training/AUPBoard/aup_hdmi_pass_thru_2023p1_working/aup_hdmi_pass_thru_2023p1/HDMI_Pass_Thru_ExDes/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.gen/sources_1/bd/exdes/exdes_ooc.xdc
