
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 8.1
 PARAMETER PROC_INSTANCE = mb_ss_0_mblaze
 PARAMETER stdin = mb_ss_0_axi_uartlite
 PARAMETER stdout = mb_ss_0_axi_uartlite
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.17
 PARAMETER HW_INSTANCE = mb_ss_0_mblaze
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = audio_ss_0_aud_pat_gen
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = clk_wiz
 PARAMETER DRIVER_VER = 1.5
 PARAMETER HW_INSTANCE = audio_ss_0_clk_wiz
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = audio_ss_0_hdmi_acr_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.16
 PARAMETER HW_INSTANCE = mb_ss_0_axi_intc
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.8
 PARAMETER HW_INSTANCE = mb_ss_0_axi_uartlite
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.8
 PARAMETER HW_INSTANCE = mb_ss_0_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.8
 PARAMETER HW_INSTANCE = mb_ss_0_ilmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = v_hdmirxss
 PARAMETER DRIVER_VER = 6.4
 PARAMETER HW_INSTANCE = v_hdmi_rx_ss
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = v_hdmitxss
 PARAMETER DRIVER_VER = 6.3
 PARAMETER HW_INSTANCE = v_hdmi_tx_ss
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.9
 PARAMETER HW_INSTANCE = v_tpg_ss_0_axi_gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = v_tpg
 PARAMETER DRIVER_VER = 8.4
 PARAMETER HW_INSTANCE = v_tpg_ss_0_v_tpg
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = vphy
 PARAMETER DRIVER_VER = 1.13
 PARAMETER HW_INSTANCE = vid_phy_controller
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.9
 PARAMETER HW_INSTANCE = mb_ss_0_axi_iic_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.9
 PARAMETER HW_INSTANCE = mb_ss_0_axi_iic_1
END


