-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (lin64) Build 6299465 Fri Nov 14 12:34:56 MST 2025
-- Date        : Wed Jan 21 12:36:57 2026
-- Host        : dan-alencar running 64-bit Linux Mint 22.2
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bd_2339_v_hdmi_tx_0_stub.vhdl
-- Design      : bd_2339_v_hdmi_tx_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcau15p-ffvb676-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_aclk : in STD_LOGIC;
    s_axi_aresetn : in STD_LOGIC;
    s_axis_video_aclk : in STD_LOGIC;
    s_axis_video_aresetn_in : in STD_LOGIC;
    s_axi_awaddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    s_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_awvalid : in STD_LOGIC;
    s_axi_awready : out STD_LOGIC;
    s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_wvalid : in STD_LOGIC;
    s_axi_wready : out STD_LOGIC;
    s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_bvalid : out STD_LOGIC;
    s_axi_bready : in STD_LOGIC;
    s_axi_araddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    s_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_arvalid : in STD_LOGIC;
    s_axi_arready : out STD_LOGIC;
    s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_rvalid : out STD_LOGIC;
    s_axi_rready : in STD_LOGIC;
    video_clk : in STD_LOGIC;
    link_clk : in STD_LOGIC;
    video_vs : in STD_LOGIC;
    video_hs : in STD_LOGIC;
    video_data : in STD_LOGIC_VECTOR ( 95 downto 0 );
    video_de : in STD_LOGIC;
    video_vs_arb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    video_hs_arb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    video_de_arb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    video_data_arb : in STD_LOGIC_VECTOR ( 95 downto 0 );
    s_axis_audio_aresetn : in STD_LOGIC;
    s_axis_audio_aclk : in STD_LOGIC;
    s_axis_audio_tready : out STD_LOGIC;
    s_axis_audio_tid : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s_axis_audio_tdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axis_audio_tvalid : in STD_LOGIC;
    acr_cts : in STD_LOGIC_VECTOR ( 19 downto 0 );
    acr_n : in STD_LOGIC_VECTOR ( 19 downto 0 );
    acr_valid : in STD_LOGIC;
    link_data0 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    link_data1 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    link_data2 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    link_valid0 : out STD_LOGIC;
    link_valid1 : out STD_LOGIC;
    link_valid2 : out STD_LOGIC;
    hpd : in STD_LOGIC;
    bridge_locked : in STD_LOGIC;
    bridge_overflow : in STD_LOGIC;
    bridge_underflow : in STD_LOGIC;
    s_axis_video_aresetn_out : out STD_LOGIC;
    video_reset : out STD_LOGIC;
    sb_status_data : in STD_LOGIC_VECTOR ( 7 downto 0 );
    sb_status_valid : in STD_LOGIC;
    m_axis_hdcp_aresetn : out STD_LOGIC;
    m_axis_hdcp_aclk : out STD_LOGIC;
    m_axis_hdcp_aclken : out STD_LOGIC;
    m_axis_hdcp_tid : out STD_LOGIC;
    m_axis_hdcp_tuser : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axis_hdcp_tdata : out STD_LOGIC_VECTOR ( 95 downto 0 );
    m_axis_hdcp_tstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axis_hdcp_tvalid : out STD_LOGIC;
    m_axis_hdcp_tlast : out STD_LOGIC;
    m_axis_hdcp_tready : in STD_LOGIC;
    s_axis_hdcp_tid : in STD_LOGIC;
    s_axis_hdcp_tuser : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axis_hdcp_tdata : in STD_LOGIC_VECTOR ( 95 downto 0 );
    s_axis_hdcp_tstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_hdcp_tvalid : in STD_LOGIC;
    s_axis_hdcp_tlast : in STD_LOGIC;
    s_axis_hdcp_tready : out STD_LOGIC;
    ddc_scl_i : in STD_LOGIC;
    ddc_scl_o : out STD_LOGIC;
    ddc_scl_t : out STD_LOGIC;
    ddc_sda_i : in STD_LOGIC;
    ddc_sda_o : out STD_LOGIC;
    ddc_sda_t : out STD_LOGIC;
    irq : out STD_LOGIC;
    vid_format_out : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bridge_yuv420 : out STD_LOGIC;
    bridge_pixel_repeat : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_2339_v_hdmi_tx_0,v_hdmi_tx_v3_0_6,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_2339_v_hdmi_tx_0,v_hdmi_tx_v3_0_6,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=v_hdmi_tx,x_ipVersion=3.0,x_ipCoreRevision=6,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_DATA_WIDTH=32,C_S_AXI_ADDR_WIDTH=9,C_BITS_PER_COMPONENT=8,C_PIXELS_PER_CLOCK=4,C_GT_LANES=4,C_HDCP_IF_ENABLE=0,C_VIDEO_MASK_ENABLE=1,C_DDC2_EN=0,C_VECTOR_DE_ENABLE=0,C_CH_WIDTH=8,C_SIM_SPEEDUP=FALSE,C_SIM_DEVICE_EN=0,C_SIM_DEVICE=VERSAL_AI_CORE_ES1,C_TST_DBG=0,x_ipLicense=v_hdmi@2017.10(design_linking)}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_aclk,s_axi_aresetn,s_axis_video_aclk,s_axis_video_aresetn_in,s_axi_awaddr[8:0],s_axi_awprot[2:0],s_axi_awvalid,s_axi_awready,s_axi_wdata[31:0],s_axi_wstrb[3:0],s_axi_wvalid,s_axi_wready,s_axi_bresp[1:0],s_axi_bvalid,s_axi_bready,s_axi_araddr[8:0],s_axi_arprot[2:0],s_axi_arvalid,s_axi_arready,s_axi_rdata[31:0],s_axi_rresp[1:0],s_axi_rvalid,s_axi_rready,video_clk,link_clk,video_vs,video_hs,video_data[95:0],video_de,video_vs_arb[3:0],video_hs_arb[3:0],video_de_arb[3:0],video_data_arb[95:0],s_axis_audio_aresetn,s_axis_audio_aclk,s_axis_audio_tready,s_axis_audio_tid[7:0],s_axis_audio_tdata[31:0],s_axis_audio_tvalid,acr_cts[19:0],acr_n[19:0],acr_valid,link_data0[39:0],link_data1[39:0],link_data2[39:0],link_valid0,link_valid1,link_valid2,hpd,bridge_locked,bridge_overflow,bridge_underflow,s_axis_video_aresetn_out,video_reset,sb_status_data[7:0],sb_status_valid,m_axis_hdcp_aresetn,m_axis_hdcp_aclk,m_axis_hdcp_aclken,m_axis_hdcp_tid,m_axis_hdcp_tuser[31:0],m_axis_hdcp_tdata[95:0],m_axis_hdcp_tstrb[3:0],m_axis_hdcp_tvalid,m_axis_hdcp_tlast,m_axis_hdcp_tready,s_axis_hdcp_tid,s_axis_hdcp_tuser[31:0],s_axis_hdcp_tdata[95:0],s_axis_hdcp_tstrb[3:0],s_axis_hdcp_tvalid,s_axis_hdcp_tlast,s_axis_hdcp_tready,ddc_scl_i,ddc_scl_o,ddc_scl_t,ddc_sda_i,ddc_sda_o,ddc_sda_t,irq,vid_format_out[1:0],bridge_yuv420,bridge_pixel_repeat";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_aclk : signal is "xilinx.com:signal:clock:1.0 S_AXI_CLK CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_aclk : signal is "XIL_INTERFACENAME S_AXI_CLK, ASSOCIATED_BUSIF S_AXI:SB_STATUS_IN, ASSOCIATED_RESET s_axi_aresetn, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_microblaze_0_clk_wiz_1_0_clk_out1, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_aresetn : signal is "xilinx.com:signal:reset:1.0 S_AXI_RST RST";
  attribute X_INTERFACE_MODE of s_axi_aresetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_aresetn : signal is "XIL_INTERFACENAME S_AXI_RST, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_video_aclk : signal is "xilinx.com:signal:clock:1.0 S_AXIS_VIDEO_ACLK CLK";
  attribute X_INTERFACE_MODE of s_axis_video_aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_video_aclk : signal is "XIL_INTERFACENAME S_AXIS_VIDEO_ACLK, ASSOCIATED_RESET s_axis_video_aresetn_in, FREQ_HZ 297000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_vid_phy_controller_0_0_tx_video_clk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_video_aresetn_in : signal is "xilinx.com:signal:reset:1.0 S_AXIS_VIDEO_ARESETN_IN RST";
  attribute X_INTERFACE_MODE of s_axis_video_aresetn_in : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_video_aresetn_in : signal is "XIL_INTERFACENAME S_AXIS_VIDEO_ARESETN_IN, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWADDR";
  attribute X_INTERFACE_MODE of s_axi_awaddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_awaddr : signal is "XIL_INTERFACENAME S_AXI, WIZ.DATA_WIDTH 32, WIZ.NUM_REG 32, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 9, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_microblaze_0_clk_wiz_1_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWPROT";
  attribute X_INTERFACE_INFO of s_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWVALID";
  attribute X_INTERFACE_INFO of s_axi_awready : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWREADY";
  attribute X_INTERFACE_INFO of s_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 S_AXI WDATA";
  attribute X_INTERFACE_INFO of s_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 S_AXI WSTRB";
  attribute X_INTERFACE_INFO of s_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI WVALID";
  attribute X_INTERFACE_INFO of s_axi_wready : signal is "xilinx.com:interface:aximm:1.0 S_AXI WREADY";
  attribute X_INTERFACE_INFO of s_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 S_AXI BRESP";
  attribute X_INTERFACE_INFO of s_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI BVALID";
  attribute X_INTERFACE_INFO of s_axi_bready : signal is "xilinx.com:interface:aximm:1.0 S_AXI BREADY";
  attribute X_INTERFACE_INFO of s_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARADDR";
  attribute X_INTERFACE_INFO of s_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARPROT";
  attribute X_INTERFACE_INFO of s_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARVALID";
  attribute X_INTERFACE_INFO of s_axi_arready : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARREADY";
  attribute X_INTERFACE_INFO of s_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 S_AXI RDATA";
  attribute X_INTERFACE_INFO of s_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 S_AXI RRESP";
  attribute X_INTERFACE_INFO of s_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI RVALID";
  attribute X_INTERFACE_INFO of s_axi_rready : signal is "xilinx.com:interface:aximm:1.0 S_AXI RREADY";
  attribute X_INTERFACE_INFO of video_clk : signal is "xilinx.com:signal:clock:1.0 VIDEO_CLK CLK";
  attribute X_INTERFACE_MODE of video_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of video_clk : signal is "XIL_INTERFACENAME VIDEO_CLK, ASSOCIATED_BUSIF VIDEO_IN, FREQ_HZ 297000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_vid_phy_controller_0_0_tx_video_clk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of link_clk : signal is "xilinx.com:signal:clock:1.0 LINK_CLK CLK";
  attribute X_INTERFACE_MODE of link_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of link_clk : signal is "XIL_INTERFACENAME LINK_CLK, ASSOCIATED_BUSIF LINK_DATA0_OUT:LINK_DATA1_OUT:LINK_DATA2_OUT, FREQ_HZ 297000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_vid_phy_controller_0_0_tx_video_clk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of video_vs : signal is "xilinx.com:interface:vid_io:1.0 VIDEO_IN VSYNC";
  attribute X_INTERFACE_MODE of video_vs : signal is "slave";
  attribute X_INTERFACE_INFO of video_hs : signal is "xilinx.com:interface:vid_io:1.0 VIDEO_IN HSYNC";
  attribute X_INTERFACE_INFO of video_data : signal is "xilinx.com:interface:vid_io:1.0 VIDEO_IN DATA";
  attribute X_INTERFACE_INFO of video_de : signal is "xilinx.com:interface:vid_io:1.0 VIDEO_IN ACTIVE_VIDEO";
  attribute X_INTERFACE_INFO of s_axis_audio_aresetn : signal is "xilinx.com:signal:reset:1.0 AUD_AXI_RST RST";
  attribute X_INTERFACE_MODE of s_axis_audio_aresetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_audio_aresetn : signal is "XIL_INTERFACENAME AUD_AXI_RST, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_audio_aclk : signal is "xilinx.com:signal:clock:1.0 AUD_AXI_CLK CLK";
  attribute X_INTERFACE_MODE of s_axis_audio_aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_audio_aclk : signal is "XIL_INTERFACENAME AUD_AXI_CLK, ASSOCIATED_BUSIF AUDIO_IN, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_microblaze_0_clk_wiz_1_0_clk_out1, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_audio_tready : signal is "xilinx.com:interface:axis:1.0 AUDIO_IN TREADY";
  attribute X_INTERFACE_MODE of s_axis_audio_tready : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_audio_tready : signal is "XIL_INTERFACENAME AUDIO_IN, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 8, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_microblaze_0_clk_wiz_1_0_clk_out1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_audio_tid : signal is "xilinx.com:interface:axis:1.0 AUDIO_IN TID";
  attribute X_INTERFACE_INFO of s_axis_audio_tdata : signal is "xilinx.com:interface:axis:1.0 AUDIO_IN TDATA";
  attribute X_INTERFACE_INFO of s_axis_audio_tvalid : signal is "xilinx.com:interface:axis:1.0 AUDIO_IN TVALID";
  attribute X_INTERFACE_INFO of link_data0 : signal is "xilinx.com:interface:axis:1.0 LINK_DATA0_OUT TDATA";
  attribute X_INTERFACE_MODE of link_data0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of link_data0 : signal is "XIL_INTERFACENAME LINK_DATA0_OUT, TDATA_NUM_BYTES 5, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 297000000, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_vid_phy_controller_0_0_tx_video_clk, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of link_data1 : signal is "xilinx.com:interface:axis:1.0 LINK_DATA1_OUT TDATA";
  attribute X_INTERFACE_MODE of link_data1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of link_data1 : signal is "XIL_INTERFACENAME LINK_DATA1_OUT, TDATA_NUM_BYTES 5, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 297000000, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_vid_phy_controller_0_0_tx_video_clk, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of link_data2 : signal is "xilinx.com:interface:axis:1.0 LINK_DATA2_OUT TDATA";
  attribute X_INTERFACE_MODE of link_data2 : signal is "master";
  attribute X_INTERFACE_PARAMETER of link_data2 : signal is "XIL_INTERFACENAME LINK_DATA2_OUT, TDATA_NUM_BYTES 5, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 297000000, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_vid_phy_controller_0_0_tx_video_clk, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of link_valid0 : signal is "xilinx.com:interface:axis:1.0 LINK_DATA0_OUT TVALID";
  attribute X_INTERFACE_INFO of link_valid1 : signal is "xilinx.com:interface:axis:1.0 LINK_DATA1_OUT TVALID";
  attribute X_INTERFACE_INFO of link_valid2 : signal is "xilinx.com:interface:axis:1.0 LINK_DATA2_OUT TVALID";
  attribute X_INTERFACE_INFO of video_reset : signal is "xilinx.com:signal:reset:1.0 VIDEO_RESET RST";
  attribute X_INTERFACE_MODE of video_reset : signal is "master";
  attribute X_INTERFACE_PARAMETER of video_reset : signal is "XIL_INTERFACENAME VIDEO_RESET, POLARITY ACTIVE_HIGH, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of sb_status_data : signal is "xilinx.com:interface:axis:1.0 SB_STATUS_IN TDATA";
  attribute X_INTERFACE_MODE of sb_status_data : signal is "slave";
  attribute X_INTERFACE_PARAMETER of sb_status_data : signal is "XIL_INTERFACENAME SB_STATUS_IN, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN hdmi_tx_bd_microblaze_0_clk_wiz_1_0_clk_out1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of sb_status_valid : signal is "xilinx.com:interface:axis:1.0 SB_STATUS_IN TVALID";
  attribute X_INTERFACE_INFO of m_axis_hdcp_aresetn : signal is "xilinx.com:signal:reset:1.0 HDCP_AXI_RST RST";
  attribute X_INTERFACE_MODE of m_axis_hdcp_aresetn : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axis_hdcp_aresetn : signal is "XIL_INTERFACENAME HDCP_AXI_RST, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axis_hdcp_aclk : signal is "xilinx.com:signal:clock:1.0 HDCP_AXI_CLK CLK";
  attribute X_INTERFACE_MODE of m_axis_hdcp_aclk : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axis_hdcp_aclk : signal is "XIL_INTERFACENAME HDCP_AXI_CLK, ASSOCIATED_BUSIF HDCP_IN:HDCP_OUT, ASSOCIATED_RESET m_axis_hdcp_aresetn, ASSOCIATED_CLKEN m_axis_hdcp_aclken, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_2339_v_hdmi_tx_0_m_axis_hdcp_aclk, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axis_hdcp_aclken : signal is "xilinx.com:signal:clockenable:1.0 HDCP_AXI_CKE CE";
  attribute X_INTERFACE_MODE of m_axis_hdcp_aclken : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axis_hdcp_aclken : signal is "XIL_INTERFACENAME HDCP_AXI_CKE, POLARITY ACTIVE_LOW";
  attribute X_INTERFACE_INFO of m_axis_hdcp_tid : signal is "xilinx.com:interface:axis:1.0 HDCP_OUT TID";
  attribute X_INTERFACE_MODE of m_axis_hdcp_tid : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axis_hdcp_tid : signal is "XIL_INTERFACENAME HDCP_OUT, TDATA_NUM_BYTES 12, TDEST_WIDTH 0, TID_WIDTH 1, TUSER_WIDTH 32, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 0, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN bd_2339_v_hdmi_tx_0_m_axis_hdcp_aclk, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axis_hdcp_tuser : signal is "xilinx.com:interface:axis:1.0 HDCP_OUT TUSER";
  attribute X_INTERFACE_INFO of m_axis_hdcp_tdata : signal is "xilinx.com:interface:axis:1.0 HDCP_OUT TDATA";
  attribute X_INTERFACE_INFO of m_axis_hdcp_tstrb : signal is "xilinx.com:interface:axis:1.0 HDCP_OUT TSTRB";
  attribute X_INTERFACE_INFO of m_axis_hdcp_tvalid : signal is "xilinx.com:interface:axis:1.0 HDCP_OUT TVALID";
  attribute X_INTERFACE_INFO of m_axis_hdcp_tlast : signal is "xilinx.com:interface:axis:1.0 HDCP_OUT TLAST";
  attribute X_INTERFACE_INFO of m_axis_hdcp_tready : signal is "xilinx.com:interface:axis:1.0 HDCP_OUT TREADY";
  attribute X_INTERFACE_INFO of s_axis_hdcp_tid : signal is "xilinx.com:interface:axis:1.0 HDCP_IN TID";
  attribute X_INTERFACE_MODE of s_axis_hdcp_tid : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_hdcp_tid : signal is "XIL_INTERFACENAME HDCP_IN, TDATA_NUM_BYTES 12, TDEST_WIDTH 0, TID_WIDTH 1, TUSER_WIDTH 32, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 0, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN bd_2339_v_hdmi_tx_0_m_axis_hdcp_aclk, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_hdcp_tuser : signal is "xilinx.com:interface:axis:1.0 HDCP_IN TUSER";
  attribute X_INTERFACE_INFO of s_axis_hdcp_tdata : signal is "xilinx.com:interface:axis:1.0 HDCP_IN TDATA";
  attribute X_INTERFACE_INFO of s_axis_hdcp_tstrb : signal is "xilinx.com:interface:axis:1.0 HDCP_IN TSTRB";
  attribute X_INTERFACE_INFO of s_axis_hdcp_tvalid : signal is "xilinx.com:interface:axis:1.0 HDCP_IN TVALID";
  attribute X_INTERFACE_INFO of s_axis_hdcp_tlast : signal is "xilinx.com:interface:axis:1.0 HDCP_IN TLAST";
  attribute X_INTERFACE_INFO of s_axis_hdcp_tready : signal is "xilinx.com:interface:axis:1.0 HDCP_IN TREADY";
  attribute X_INTERFACE_INFO of ddc_scl_i : signal is "xilinx.com:interface:iic:1.0 DDC_OUT SCL_I";
  attribute X_INTERFACE_MODE of ddc_scl_i : signal is "master";
  attribute X_INTERFACE_INFO of ddc_scl_o : signal is "xilinx.com:interface:iic:1.0 DDC_OUT SCL_O";
  attribute X_INTERFACE_INFO of ddc_scl_t : signal is "xilinx.com:interface:iic:1.0 DDC_OUT SCL_T";
  attribute X_INTERFACE_INFO of ddc_sda_i : signal is "xilinx.com:interface:iic:1.0 DDC_OUT SDA_I";
  attribute X_INTERFACE_INFO of ddc_sda_o : signal is "xilinx.com:interface:iic:1.0 DDC_OUT SDA_O";
  attribute X_INTERFACE_INFO of ddc_sda_t : signal is "xilinx.com:interface:iic:1.0 DDC_OUT SDA_T";
  attribute X_INTERFACE_INFO of irq : signal is "xilinx.com:signal:interrupt:1.0 IRQ_SIGNAL_INTERRUPT INTERRUPT";
  attribute X_INTERFACE_MODE of irq : signal is "master";
  attribute X_INTERFACE_PARAMETER of irq : signal is "XIL_INTERFACENAME IRQ_SIGNAL_INTERRUPT, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "v_hdmi_tx_v3_0_6,Vivado 2025.2";
begin
end;
