// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module exdes_v_tpg_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sof,
        div228_cast,
        ovrlayYUV_dout,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        ovrlayYUV_empty_n,
        ovrlayYUV_read,
        colorFormat_load,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        sub_cast,
        counter_loc_1_out_i,
        counter_loc_1_out_o,
        counter_loc_1_out_o_ap_vld,
        phi_ln991_out,
        phi_ln991_out_ap_vld,
        counter,
        counter_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_state4 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] sof;
input  [11:0] div228_cast;
input  [47:0] ovrlayYUV_dout;
input  [4:0] ovrlayYUV_num_data_valid;
input  [4:0] ovrlayYUV_fifo_cap;
input   ovrlayYUV_empty_n;
output   ovrlayYUV_read;
input  [7:0] colorFormat_load;
output  [47:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [5:0] m_axis_video_TKEEP;
output  [5:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [11:0] sub_cast;
input  [15:0] counter_loc_1_out_i;
output  [15:0] counter_loc_1_out_o;
output   counter_loc_1_out_o_ap_vld;
output  [0:0] phi_ln991_out;
output   phi_ln991_out_ap_vld;
output  [15:0] counter;
output   counter_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ovrlayYUV_read;
reg m_axis_video_TVALID;
reg[15:0] counter_loc_1_out_o;
reg counter_loc_1_out_o_ap_vld;
reg phi_ln991_out_ap_vld;
reg counter_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ovrlayYUV_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln936_reg_505;
reg    m_axis_video_TDATA_blk_n;
reg   [0:0] sof_2_reg_194;
reg   [0:0] phi_ln991_reg_206;
wire  signed [12:0] sub_cast_cast_fu_219_p1;
reg  signed [12:0] sub_cast_cast_reg_500;
wire   [0:0] icmp_ln936_fu_235_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] axi_last_fu_246_p2;
reg   [0:0] axi_last_reg_509;
wire   [0:0] trunc_ln963_fu_282_p1;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg   [0:0] ap_phi_mux_sof_2_phi_fu_198_p4;
wire   [15:0] add_ln960_fu_255_p2;
reg   [11:0] j_fu_124;
wire   [11:0] j_2_fu_240_p2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state4;
wire   [12:0] zext_ln936_fu_231_p1;
wire   [7:0] pix_444_fu_286_p1;
wire   [7:0] pix_rgb_4_fu_310_p4;
wire   [0:0] icmp_ln975_1_fu_361_p2;
wire   [8:0] axi_data_1_fu_348_p3;
wire   [8:0] axi_data_fu_340_p3;
wire   [8:0] axi_data_2_fu_366_p3;
wire   [7:0] pix_rgb_5_fu_320_p4;
wire   [0:0] icmp_ln975_fu_356_p2;
wire   [7:0] pix_422_fu_330_p4;
wire   [7:0] select_ln975_1_fu_386_p3;
wire   [7:0] pix_rgb_fu_290_p4;
wire   [7:0] select_ln975_3_fu_402_p3;
wire   [7:0] pix_rgb_6_fu_300_p4;
wire   [7:0] select_ln975_5_fu_418_p3;
wire   [7:0] select_ln975_7_fu_434_p3;
wire   [7:0] select_ln975_8_fu_442_p3;
wire   [7:0] select_ln975_6_fu_426_p3;
wire   [7:0] select_ln975_4_fu_410_p3;
wire   [7:0] select_ln975_2_fu_394_p3;
wire   [7:0] select_ln975_fu_378_p3;
wire  signed [47:0] sext_ln880_fu_374_p1;
wire   [39:0] tmp_s_fu_450_p6;
wire    ap_CS_fsm_state5;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_124 <= 12'd0;
    end else if (((icmp_ln936_fu_235_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        j_fu_124 <= j_2_fu_240_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_ln991_reg_206 <= 1'd0;
    end else if (((icmp_ln936_reg_505 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phi_ln991_reg_206 <= trunc_ln963_fu_282_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_2_reg_194 <= sof;
    end else if (((icmp_ln936_reg_505 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sof_2_reg_194 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln936_fu_235_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        axi_last_reg_509 <= axi_last_fu_246_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln936_reg_505 <= icmp_ln936_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sub_cast_cast_reg_500 <= sub_cast_cast_fu_219_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln936_fu_235_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln936_reg_505 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_sof_2_phi_fu_198_p4 = 1'd0;
    end else begin
        ap_phi_mux_sof_2_phi_fu_198_p4 = sof_2_reg_194;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln936_fu_235_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_sof_2_phi_fu_198_p4 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        counter_ap_vld = 1'b1;
    end else begin
        counter_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln936_fu_235_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_sof_2_phi_fu_198_p4 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        counter_loc_1_out_o = add_ln960_fu_255_p2;
    end else begin
        counter_loc_1_out_o = counter_loc_1_out_i;
    end
end

always @ (*) begin
    if (((icmp_ln936_fu_235_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_sof_2_phi_fu_198_p4 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        counter_loc_1_out_o_ap_vld = 1'b1;
    end else begin
        counter_loc_1_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln936_reg_505 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_video_TDATA_blk_n = m_axis_video_TREADY;
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln936_reg_505 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_video_TVALID = 1'b1;
    end else begin
        m_axis_video_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln936_reg_505 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ovrlayYUV_blk_n = ovrlayYUV_empty_n;
    end else begin
        ovrlayYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln936_reg_505 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ovrlayYUV_read = 1'b1;
    end else begin
        ovrlayYUV_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        phi_ln991_out_ap_vld = 1'b1;
    end else begin
        phi_ln991_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln936_fu_235_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((icmp_ln936_fu_235_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln960_fu_255_p2 = (counter_loc_1_out_i + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln936_reg_505 == 1'd0) & (m_axis_video_TREADY == 1'b0)) | ((icmp_ln936_reg_505 == 1'd0) & (ovrlayYUV_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln936_reg_505 == 1'd0) & (m_axis_video_TREADY == 1'b0)) | ((icmp_ln936_reg_505 == 1'd0) & (ovrlayYUV_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln936_reg_505 == 1'd0) & (m_axis_video_TREADY == 1'b0)) | ((icmp_ln936_reg_505 == 1'd0) & (ovrlayYUV_empty_n == 1'b0))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((icmp_ln936_reg_505 == 1'd0) & (m_axis_video_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((icmp_ln936_reg_505 == 1'd0) & (m_axis_video_TREADY == 1'b0)) | ((icmp_ln936_reg_505 == 1'd0) & (ovrlayYUV_empty_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign axi_data_1_fu_348_p3 = {{1'd1}, {pix_rgb_4_fu_310_p4}};

assign axi_data_2_fu_366_p3 = ((icmp_ln975_1_fu_361_p2[0:0] == 1'b1) ? axi_data_1_fu_348_p3 : axi_data_fu_340_p3);

assign axi_data_fu_340_p3 = {{1'd1}, {pix_444_fu_286_p1}};

assign axi_last_fu_246_p2 = ((zext_ln936_fu_231_p1 == sub_cast_cast_reg_500) ? 1'b1 : 1'b0);

assign counter = (counter_loc_1_out_i + 16'd1);

assign icmp_ln936_fu_235_p2 = ((j_fu_124 == div228_cast) ? 1'b1 : 1'b0);

assign icmp_ln975_1_fu_361_p2 = ((colorFormat_load == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln975_fu_356_p2 = ((colorFormat_load == 8'd1) ? 1'b1 : 1'b0);

assign j_2_fu_240_p2 = (j_fu_124 + 12'd1);

assign m_axis_video_TDATA = {{tmp_s_fu_450_p6}, {sext_ln880_fu_374_p1[7:0]}};

assign m_axis_video_TDEST = 1'd0;

assign m_axis_video_TID = 1'd0;

assign m_axis_video_TKEEP = 6'd63;

assign m_axis_video_TLAST = axi_last_reg_509;

assign m_axis_video_TSTRB = 6'd0;

assign m_axis_video_TUSER = sof_2_reg_194;

assign phi_ln991_out = phi_ln991_reg_206;

assign pix_422_fu_330_p4 = {{ovrlayYUV_dout[31:24]}};

assign pix_444_fu_286_p1 = ovrlayYUV_dout[7:0];

assign pix_rgb_4_fu_310_p4 = {{ovrlayYUV_dout[15:8]}};

assign pix_rgb_5_fu_320_p4 = {{ovrlayYUV_dout[23:16]}};

assign pix_rgb_6_fu_300_p4 = {{ovrlayYUV_dout[47:40]}};

assign pix_rgb_fu_290_p4 = {{ovrlayYUV_dout[39:32]}};

assign select_ln975_1_fu_386_p3 = ((icmp_ln975_fu_356_p2[0:0] == 1'b1) ? pix_rgb_5_fu_320_p4 : pix_422_fu_330_p4);

assign select_ln975_2_fu_394_p3 = ((icmp_ln975_1_fu_361_p2[0:0] == 1'b1) ? pix_444_fu_286_p1 : select_ln975_1_fu_386_p3);

assign select_ln975_3_fu_402_p3 = ((icmp_ln975_fu_356_p2[0:0] == 1'b1) ? pix_422_fu_330_p4 : pix_rgb_fu_290_p4);

assign select_ln975_4_fu_410_p3 = ((icmp_ln975_1_fu_361_p2[0:0] == 1'b1) ? pix_rgb_fu_290_p4 : select_ln975_3_fu_402_p3);

assign select_ln975_5_fu_418_p3 = ((icmp_ln975_fu_356_p2[0:0] == 1'b1) ? pix_rgb_fu_290_p4 : pix_rgb_6_fu_300_p4);

assign select_ln975_6_fu_426_p3 = ((icmp_ln975_1_fu_361_p2[0:0] == 1'b1) ? pix_rgb_6_fu_300_p4 : select_ln975_5_fu_418_p3);

assign select_ln975_7_fu_434_p3 = ((icmp_ln975_fu_356_p2[0:0] == 1'b1) ? pix_rgb_6_fu_300_p4 : pix_rgb_5_fu_320_p4);

assign select_ln975_8_fu_442_p3 = ((icmp_ln975_1_fu_361_p2[0:0] == 1'b1) ? pix_422_fu_330_p4 : select_ln975_7_fu_434_p3);

assign select_ln975_fu_378_p3 = ((icmp_ln975_1_fu_361_p2[0:0] == 1'b1) ? pix_rgb_5_fu_320_p4 : pix_rgb_4_fu_310_p4);

assign sext_ln880_fu_374_p1 = $signed(axi_data_2_fu_366_p3);

assign sub_cast_cast_fu_219_p1 = $signed(sub_cast);

assign tmp_s_fu_450_p6 = {{{{{select_ln975_8_fu_442_p3}, {select_ln975_6_fu_426_p3}}, {select_ln975_4_fu_410_p3}}, {select_ln975_2_fu_394_p3}}, {select_ln975_fu_378_p3}};

assign trunc_ln963_fu_282_p1 = counter_loc_1_out_i[0:0];

assign zext_ln936_fu_231_p1 = j_fu_124;

endmodule //exdes_v_tpg_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2
