function fluidtopicsclient(){var P='bootstrap',Q='begin',R='gwt.codesvr.fluidtopicsclient=',S='gwt.codesvr=',T='fluidtopicsclient',U='startup',V='DUMMY',W=0,X=1,Y='iframe',Z='position:absolute; width:0; height:0; border:none; left: -1000px; top: -1000px;',$='fluidtopicsclient-hostframe.html',_='true',ab='undefined',bb='readystatechange',cb=10,db='ready',eb='Chrome',fb='script',gb='',hb='moduleStartup',ib='moduleRequested',jb='Failed to load ',kb='head',lb='javascript',mb='meta',nb='name',ob='fluidtopicsclient::',pb='::',qb='gwt:property',rb='content',sb='=',tb='gwt:onPropertyErrorFn',ub='Bad handler "',vb='" for "gwt:onPropertyErrorFn"',wb='gwt:onLoadErrorFn',xb='" for "gwt:onLoadErrorFn"',yb='#',zb='?',Ab='/',Bb='img',Cb='clear.cache.gif',Db='baseUrl',Eb='fluidtopicsclient.nocache.js',Fb='base',Gb='//',Hb='user.agent',Ib='webkit',Jb='safari',Kb='gecko',Lb='gecko1_8',Mb='selectingPermutation',Nb='fluidtopicsclient.devmode.js',Ob='A949132DB5BD854D614DFD4F75395099',Pb='FF57595740745487D742C76E53CD50D4',Qb=':',Rb='.cache.js',Sb='loadExternalRefs',Tb='end',Ub='http:',Vb='https:',Wb='_gwt_dummy_',Xb='__gwtDevModeHook:fluidtopicsclient',Yb='Dev Mode URL does not match webapp URL: ',Zb=' vs ',$b=':moduleBase';var o=window;var p=document;r(P,Q);function q(){var a=o.location.search;return a.indexOf(R)!=-1||a.indexOf(S)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:T,sessionId:o.__gwtStatsSessionId,subSystem:U,evtGroup:a,millis:(new Date).getTime(),type:b})}}
fluidtopicsclient.__sendStats=r;fluidtopicsclient.__moduleName=T;fluidtopicsclient.__errFn=null;fluidtopicsclient.__moduleBase=V;fluidtopicsclient.__softPermutationId=W;fluidtopicsclient.__computePropValue=null;fluidtopicsclient.__getPropMap=null;fluidtopicsclient.__installRunAsyncCode=function(){};fluidtopicsclient.__gwtStartLoadingFragment=function(){return null};fluidtopicsclient.__gwt_isKnownPropertyValue=function(){return false};fluidtopicsclient.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[T]={moduleName:T};fluidtopicsclient.__moduleStartupDone=function(e){var f=t[T].bindings;t[T].bindings=function(){var a=f?f():{};var b=e[fluidtopicsclient.__softPermutationId];for(var c=W;c<b.length;c++){var d=b[c];a[d[W]]=d[X]}return a}};var u;function v(){w();return p.getElementById(T).contentWindow.document}
function w(){if(u){return}var a;if(o.__gwt_activeModules[T].superdevmode){a=o.__gwt_ft_moduleBase}else{a=o.__gwt_activeModules[T].moduleBase}var b=p.createElement(Y);b.id=T;b.style.cssText=Z;b.tabIndex=-1;b.src=a+$;b.ariaHidden=_;p.body.appendChild(b);u=true}
function A(i){function j(a){function b(){if(typeof p.readyState==ab){return typeof p.body!=ab&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();var d=c&&l();if(d){a();return}function e(){if(!c){if(!b()){return}c=true;k(a);if(p.removeEventListener){p.removeEventListener(bb,e,false)}if(f){clearInterval(f)}}}
if(p.addEventListener){p.addEventListener(bb,e,false)}if(!c){var f=setInterval(function(){e()},cb)}}
function k(a){var b=l();if(b){a();return}var c=setInterval(function(){b=l();if(b){clearInterval(c);a()}},cb)}
function l(){var a=v();return a&&(a.body&&a.body.innerText===db)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(eb)>-1){g=e.createElement(fb);g.text=c.join(gb);f.appendChild(g);d(f,g)}else{for(var h=W;h<c.length;h++){g=e.createElement(fb);g.text=c[h];f.appendChild(g);d(f,g)}}}
fluidtopicsclient.onScriptDownloaded=function(a){j(function(){m(a)})};r(hb,ib);var n=p.createElement(fb);n.src=i;if(fluidtopicsclient.__errFn){n.onerror=function(){fluidtopicsclient.__errFn(T,new Error(jb+code))}}p.getElementsByTagName(kb)[W].appendChild(n)}
fluidtopicsclient.__startLoadingFragment=function(a){return F(a)};fluidtopicsclient.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(fb);d.language=lb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(mb);for(var g=W,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(nb),k;if(j){j=j.replace(ob,gb);if(j.indexOf(pb)>=W){continue}if(j==qb){k=i.getAttribute(rb);if(k){var l,m=k.indexOf(sb);if(m>=W){j=k.substring(W,m);l=k.substring(m+X)}else{j=k;l=gb}c[j]=l}}else if(j==tb){k=i.getAttribute(rb);if(k){try{d=eval(k)}catch(a){alert(ub+k+vb)}}}else if(j==wb){k=i.getAttribute(rb);if(k){try{e=eval(k)}catch(a){alert(ub+k+xb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;fluidtopicsclient.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(yb);if(b==-1){b=a.length}var c=a.indexOf(zb);if(c==-1){c=a.length}var d=a.lastIndexOf(Ab,Math.min(c,b));return d>=W?a.substring(W,d+X):gb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Bb);b.src=a+Cb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Db);if(a!=null){return a}return gb}
function h(){var a=p.getElementsByTagName(fb);for(var b=W;b<a.length;++b){if(a[b].src.indexOf(Eb)!=-1){return e(a[b].src)}}return gb}
function i(){var a=p.getElementsByTagName(Fb);if(a.length>W){return a[a.length-X].href}return gb}
function j(){var a=p.location;return a.href==a.protocol+Gb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==gb){k=h()}if(k==gb){k=i()}if(k==gb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(){var a=C();if(!o.__gwt_activeModules[T].superdevmode){o.__gwt_ft_moduleBase=a}return a}
function F(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return fluidtopicsclient.__moduleBase+a}
function G(){var f=[];var g=W;function h(a,b){var c=f;for(var d=W,e=a.length-X;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Hb]=function(){var a=navigator.userAgent.toLowerCase();if(function(){return a.indexOf(Ib)!=-1}())return Jb;if(function(){return a.indexOf(Kb)!=-1}())return Lb;return Lb};i[Hb]={'gecko1_8':W,'safari':X};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};fluidtopicsclient.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};fluidtopicsclient.__computePropValue=k;o.__gwt_activeModules[T].bindings=fluidtopicsclient.__getPropMap;r(P,Mb);if(q()){return F(Nb)}var l;try{h([Lb],Ob);h([Jb],Pb);l=f[k(Hb)];var m=l.indexOf(Qb);if(m!=-1){g=parseInt(l.substring(m+X),cb);l=l.substring(W,m)}}catch(a){}fluidtopicsclient.__softPermutationId=g;return F(l+Rb)}
function H(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Sb,Q);r(Sb,Tb)}
B();fluidtopicsclient.__moduleBase=D();t[T].moduleBase=fluidtopicsclient.__moduleBase;var I=G();if(o){var J=!!(o.location.protocol==Ub||o.location.protocol==Vb);o.__gwt_activeModules[T].canRedirect=J;function K(){var b=Wb;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(J&&K()){var L=Xb;var M=o.sessionStorage[L];if(!(new RegExp(window.__gwt_ft_moduleBase)).test(M)){if(M&&(window.console&&console.log)){console.log(Yb+M+Zb+window.__gwt_ft_moduleBase)}M=gb}if(M&&!o[L]){o[L]=true;o[L+$b]=D();var N=p.createElement(fb);N.src=M;var O=p.getElementsByTagName(kb)[W];O.insertBefore(N,O.firstElementChild||O.children[W]);return false}}}H();r(P,Tb);A(I);return true}
fluidtopicsclient.succeeded=fluidtopicsclient();