#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x1ffff
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 0x20
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_XBRAM_0_BASEADDR 0x0
#define XPAR_XBRAM_0_HIGHADDR 0x1ffff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_IIC_0 */
#define XPAR_AXI_IIC_0_COMPATIBLE "xlnx,axi-iic-2.1"
#define XPAR_AXI_IIC_0_BASEADDR 0x40800000
#define XPAR_AXI_IIC_0_HIGHADDR 0x4080ffff
#define XPAR_AXI_IIC_0_TEN_BIT_ADR 0x0
#define XPAR_AXI_IIC_0_GPO_WIDTH 0x1
#define XPAR_AXI_IIC_0_INTERRUPTS 0x2001
#define XPAR_FABRIC_AXI_IIC_0_INTR 1
#define XPAR_AXI_IIC_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_IIC_0 */
#define XPAR_XIIC_0_BASEADDR 0x40800000
#define XPAR_FABRIC_XIIC_0_INTR 1
#define XPAR_XIIC_0_HIGHADDR 0x4080ffff
#define XPAR_XIIC_0_COMPATIBLE "xlnx,axi-iic-2.1"
#define XPAR_XIIC_0_GPO_WIDTH 0x1
#define XPAR_XIIC_0_INTERRUPTS 0x2001
#define XPAR_XIIC_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XIIC_0_TEN_BIT_ADR 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 0x2
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_SW_INTR 0x3
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_IVR 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_CIE 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_SIE 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_IPR 0x1

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x1
#define XPAR_XINTC_0_HAS_CIE 0x1
#define XPAR_XINTC_0_HAS_SIE 0x1
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x0
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_NUM_SW_INTR 0x3

#define XPAR_XV_HDMITX_NUM_INSTANCES 1

/* Definitions for peripheral V_HDMI_TX_SS_0_V_HDMI_TX */
#define XPAR_V_HDMI_TX_SS_0_V_HDMI_TX_COMPATIBLE "xlnx,v-hdmi-tx-3.0"
#define XPAR_V_HDMI_TX_SS_0_V_HDMI_TX_BASEADDR 0x44a00000
#define XPAR_V_HDMI_TX_SS_0_V_HDMI_TX_HIGHADDR 0x44a0ffff
#define XPAR_V_HDMI_TX_SS_0_V_HDMI_TX_AXI_LITE_FREQ_HZ 0x5f5e100

/* Canonical definitions for peripheral V_HDMI_TX_SS_0_V_HDMI_TX */
#define XPAR_XV_HDMITX_0_BASEADDR 0x44a00000
#define XPAR_XV_HDMITX_0_HIGHADDR 0x44a0ffff
#define XPAR_XV_HDMITX_0_AXI_LITE_FREQ_HZ 0x5f5e100
#define XPAR_XV_HDMITX_0_COMPATIBLE "xlnx,v-hdmi-tx-3.0"

#define XPAR_XV_HDMITXSS_NUM_INSTANCES 1

/* Definitions for peripheral V_HDMI_TX_SS_0 */
#define XPAR_V_HDMI_TX_SS_0_COMPATIBLE "xlnx,v-hdmi-tx-ss-3.2"
#define XPAR_V_HDMI_TX_SS_0_BASEADDR 0x44a00000
#define XPAR_V_HDMI_TX_SS_0_HIGHADDR 0x44a1ffff
#define XPAR_V_HDMI_TX_SS_0_HIGHADDR 0x44a1ffff
#define XPAR_V_HDMI_TX_SS_0_INPUT_PIXELS_PER_CLOCK 0x4
#define XPAR_V_HDMI_TX_SS_0_MAX_BITS_PER_COMPONENT 0x8
#define XPAR_V_HDMI_TX_SS_0_INCLUDE_LOW_RESO_VID 0x1
#define XPAR_V_HDMI_TX_SS_0_INCLUDE_YUV420_SUP 0x1
#define XPAR_V_HDMI_TX_SS_0_AXI_LITE_FREQ_HZ 0x5f5e100
#define XPAR_V_HDMI_TX_SS_0_HDCPTIMER_PRESENT 0x0
#define XPAR_V_HDMI_TX_SS_0_HDCP14_PRESENT 0x0
#define XPAR_V_HDMI_TX_SS_0_HDCP22_PRESENT 0x0
#define XPAR_V_HDMI_TX_SS_0_HDMITX_PRESENT 0x1
#define XPAR_V_HDMI_TX_SS_0_HDMITX_CONNECTED 0x44a00000
#define XPAR_V_HDMI_TX_SS_0_VTC_PRESENT 0x1
#define XPAR_V_HDMI_TX_SS_0_VTC_CONNECTED 0x44a10000
#define XPAR_V_HDMI_TX_SS_0_INTERRUPTS 0x2000
#define XPAR_FABRIC_V_HDMI_TX_SS_0_INTR 0
#define XPAR_V_HDMI_TX_SS_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral V_HDMI_TX_SS_0 */
#define XPAR_XV_HDMITXSS_0_BASEADDR 0x44a00000
#define XPAR_FABRIC_XV_HDMITXSS_0_INTR 0
#define XPAR_XV_HDMITXSS_0_HIGHADDR 0x44a1ffff
#define XPAR_XV_HDMITXSS_0_AXI_LITE_FREQ_HZ 0x5f5e100
#define XPAR_XV_HDMITXSS_0_COMPATIBLE "xlnx,v-hdmi-tx-ss-3.2"
#define XPAR_XV_HDMITXSS_0_HIGHADDR 0x44a1ffff
#define XPAR_XV_HDMITXSS_0_HDCPTIMER_PRESENT 0x0
#define XPAR_XV_HDMITXSS_0_HDCP14_PRESENT 0x0
#define XPAR_XV_HDMITXSS_0_HDCP22_PRESENT 0x0
#define XPAR_XV_HDMITXSS_0_HDMITX_PRESENT 0x1
#define XPAR_XV_HDMITXSS_0_HDMITX_CONNECTED 0x44a00000
#define XPAR_XV_HDMITXSS_0_INPUT_PIXELS_PER_CLOCK 0x4
#define XPAR_XV_HDMITXSS_0_INCLUDE_LOW_RESO_VID 0x1
#define XPAR_XV_HDMITXSS_0_INCLUDE_YUV420_SUP 0x1
#define XPAR_XV_HDMITXSS_0_INTERRUPTS 0x2000
#define XPAR_XV_HDMITXSS_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XV_HDMITXSS_0_MAX_BITS_PER_COMPONENT 0x8
#define XPAR_XV_HDMITXSS_0_VTC_PRESENT 0x1
#define XPAR_XV_HDMITXSS_0_VTC_CONNECTED 0x44a10000

#define XPAR_XV_TPG_NUM_INSTANCES 1

/* Definitions for peripheral V_TPG_0 */
#define XPAR_V_TPG_0_COMPATIBLE "xlnx,v-tpg-8.2"
#define XPAR_V_TPG_0_BASEADDR 0x44a20000
#define XPAR_V_TPG_0_HIGHADDR 0x44a2ffff
#define XPAR_V_TPG_0_SAMPLES_PER_CLOCK 0x4
#define XPAR_V_TPG_0_NUM_VIDEO_COMPONENTS 0x3
#define XPAR_V_TPG_0_MAX_COLS 0x780
#define XPAR_V_TPG_0_MAX_ROWS 0x438
#define XPAR_V_TPG_0_MAX_DATA_WIDTH 0x8
#define XPAR_V_TPG_0_SOLID_COLOR 0x1
#define XPAR_V_TPG_0_RAMP 0x1
#define XPAR_V_TPG_0_COLOR_BAR 0x1
#define XPAR_V_TPG_0_DISPLAY_PORT 0x1
#define XPAR_V_TPG_0_COLOR_SWEEP 0x1
#define XPAR_V_TPG_0_ZONE_PLATE 0x1
#define XPAR_V_TPG_0_FOREGROUND 0x1

/* Canonical definitions for peripheral V_TPG_0 */
#define XPAR_XV_TPG_0_BASEADDR 0x44a20000
#define XPAR_XV_TPG_0_HIGHADDR 0x44a2ffff
#define XPAR_XV_TPG_0_COMPATIBLE "xlnx,v-tpg-8.2"
#define XPAR_XV_TPG_0_COLOR_BAR 0x1
#define XPAR_XV_TPG_0_COLOR_SWEEP 0x1
#define XPAR_XV_TPG_0_DISPLAY_PORT 0x1
#define XPAR_XV_TPG_0_FOREGROUND 0x1
#define XPAR_XV_TPG_0_MAX_COLS 0x780
#define XPAR_XV_TPG_0_MAX_ROWS 0x438
#define XPAR_XV_TPG_0_MAX_DATA_WIDTH 0x8
#define XPAR_XV_TPG_0_NUM_VIDEO_COMPONENTS 0x3
#define XPAR_XV_TPG_0_RAMP 0x1
#define XPAR_XV_TPG_0_SAMPLES_PER_CLOCK 0x4
#define XPAR_XV_TPG_0_SOLID_COLOR 0x1
#define XPAR_XV_TPG_0_ZONE_PLATE 0x1

#define XPAR_XVPHY_NUM_INSTANCES 1

/* Definitions for peripheral VID_PHY_CONTROLLER_0 */
#define XPAR_VID_PHY_CONTROLLER_0_COMPATIBLE "xlnx,vid-phy-controller-2.2"
#define XPAR_VID_PHY_CONTROLLER_0_BASEADDR 0x44a30000
#define XPAR_VID_PHY_CONTROLLER_0_HIGHADDR 0x44a3ffff
#define XPAR_VID_PHY_CONTROLLER_0_TRANSCEIVER_TYPE 0x5
#define XPAR_VID_PHY_CONTROLLER_0_TX_NO_OF_CHANNELS 0x3
#define XPAR_VID_PHY_CONTROLLER_0_RX_NO_OF_CHANNELS 0x3
#define XPAR_VID_PHY_CONTROLLER_0_TX_PROTOCOL 0x1
#define XPAR_VID_PHY_CONTROLLER_0_RX_PROTOCOL 0x3
#define XPAR_VID_PHY_CONTROLLER_0_TX_REFCLK_SEL 0x0
#define XPAR_VID_PHY_CONTROLLER_0_RX_REFCLK_SEL 0x1
#define XPAR_VID_PHY_CONTROLLER_0_TX_PLL_SELECTION 0x6
#define XPAR_VID_PHY_CONTROLLER_0_RX_PLL_SELECTION 0x0
#define XPAR_VID_PHY_CONTROLLER_0_NIDRU 0x0
#define XPAR_VID_PHY_CONTROLLER_0_NIDRU_REFCLK_SEL 0x0
#define XPAR_VID_PHY_CONTROLLER_0_INPUT_PIXELS_PER_CLOCK 0x4
#define XPAR_VID_PHY_CONTROLLER_0_TX_BUFFER_BYPASS 0x1
#define XPAR_VID_PHY_CONTROLLER_0_HDMI_FAST_SWITCH 0x1
#define XPAR_VID_PHY_CONTROLLER_0_TRANSCEIVER_WIDTH 0x4
#define XPAR_VID_PHY_CONTROLLER_0_ERR_IRQ_EN 0x0
#define XPAR_VID_PHY_CONTROLLER_0_AXI_ACLK_FREQ_MHZ 0x5f5e100
#define XPAR_VID_PHY_CONTROLLER_0_DRPCLK_FREQ 0x5f5e100
#define XPAR_VID_PHY_CONTROLLER_0_USE_GT_CH4_HDMI 0x0
#define XPAR_VID_PHY_CONTROLLER_0_TX_DP_PROTOCOL 0x0
#define XPAR_VID_PHY_CONTROLLER_0_RX_DP_PROTOCOL 0x0
#define XPAR_VID_PHY_CONTROLLER_0_TX_CLK_PRIMITIVE 0x0
#define XPAR_VID_PHY_CONTROLLER_0_RX_CLK_PRIMITIVE 0x0

/* Canonical definitions for peripheral VID_PHY_CONTROLLER_0 */
#define XPAR_XVPHY_0_BASEADDR 0x44a30000
#define XPAR_XVPHY_0_HIGHADDR 0x44a3ffff
#define XPAR_XVPHY_0_AXI_ACLK_FREQ_MHZ 0x5f5e100
#define XPAR_XVPHY_0_COMPATIBLE "xlnx,vid-phy-controller-2.2"
#define XPAR_XVPHY_0_DRPCLK_FREQ 0x5f5e100
#define XPAR_XVPHY_0_ERR_IRQ_EN 0x0
#define XPAR_XVPHY_0_HDMI_FAST_SWITCH 0x1
#define XPAR_XVPHY_0_INPUT_PIXELS_PER_CLOCK 0x4
#define XPAR_XVPHY_0_NIDRU 0x0
#define XPAR_XVPHY_0_NIDRU_REFCLK_SEL 0x0
#define XPAR_XVPHY_0_RX_NO_OF_CHANNELS 0x3
#define XPAR_XVPHY_0_RX_PROTOCOL 0x3
#define XPAR_XVPHY_0_RX_REFCLK_SEL 0x1
#define XPAR_XVPHY_0_RX_PLL_SELECTION 0x0
#define XPAR_XVPHY_0_RX_DP_PROTOCOL 0x0
#define XPAR_XVPHY_0_RX_CLK_PRIMITIVE 0x0
#define XPAR_XVPHY_0_TRANSCEIVER_TYPE 0x5
#define XPAR_XVPHY_0_TX_NO_OF_CHANNELS 0x3
#define XPAR_XVPHY_0_TX_PROTOCOL 0x1
#define XPAR_XVPHY_0_TX_REFCLK_SEL 0x0
#define XPAR_XVPHY_0_TX_PLL_SELECTION 0x6
#define XPAR_XVPHY_0_TX_BUFFER_BYPASS 0x1
#define XPAR_XVPHY_0_TRANSCEIVER_WIDTH 0x4
#define XPAR_XVPHY_0_TX_DP_PROTOCOL 0x0
#define XPAR_XVPHY_0_TX_CLK_PRIMITIVE 0x0
#define XPAR_XVPHY_0_USE_GT_CH4_HDMI 0x0

#define XPAR_XVTC_NUM_INSTANCES 1

/* Definitions for peripheral V_HDMI_TX_SS_0_V_TC */
#define XPAR_V_HDMI_TX_SS_0_V_TC_COMPATIBLE "xlnx,v-tc-6.2"
#define XPAR_V_HDMI_TX_SS_0_V_TC_BASEADDR 0x44a10000
#define XPAR_V_HDMI_TX_SS_0_V_TC_HIGHADDR 0x44a1ffff

/* Canonical definitions for peripheral V_HDMI_TX_SS_0_V_TC */
#define XPAR_XVTC_0_BASEADDR 0x44a10000
#define XPAR_XVTC_0_HIGHADDR 0x44a1ffff
#define XPAR_XVTC_0_COMPATIBLE "xlnx,v-tc-6.2"

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x1ffff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_EXCEPTIONS_IN_DELAY_SLOTS 1
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_USE_MSR_INSTR 1
#define XPAR_MICROBLAZE_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_D_CACHE_SIZE 4096
#define XPAR_MICROBLAZE_I_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_I_CACHE_SIZE 4096
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 0
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 1
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 4096
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 0
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 4096
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_TIMEBASE_FREQUENCY 100000000
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 1
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 2
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER2 0
#define XPAR_MICROBLAZE_RESET_MSR 0
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_USE_BARREL 1
#define XPAR_MICROBLAZE_USE_DCACHE 0
#define XPAR_MICROBLAZE_USE_DIV 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 1
#define XPAR_MICROBLAZE_USE_ICACHE 0
#define XPAR_MICROBLAZE_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 1
#define XPAR_MICROBLAZE_D_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_D_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_I_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_I_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_REG 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_DDR_RESERVE_SA 0

#define XPAR_MICROBLAZE_ADDR_SIZE 32

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "xcau15p"

#endif  /* end of protection macro */