#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Script generated by Vivado on Wed Jan 21 15:11:21 -03 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : hdmi_tx_bd.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : hdmi_tx_bd.sh
#                hdmi_tx_bd.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                hdmi_tx_bd.sh [-rerun]
#                hdmi_tx_bd.sh [-reset_run]
#                hdmi_tx_bd.sh [-clean]
#                hdmi_tx_bd.sh [-reset_log]
#                hdmi_tx_bd.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'hdmi_tx_bd.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************
export SIM_VER_XCELIUM=
export GCC_VER_XCELIUM=

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +r -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname v_hdmi_tx_v3_0_6 -libname xil_defaultlib -libname axi_lite_ipif_v3_0_4 -libname v_tc_v6_2_11 -libname v_tc_v6_1_14 -libname v_vid_in_axi4s_v4_0_11 -libname v_axi4s_vid_out_v4_0_20 -libname proc_sys_reset_v5_0_17 -libname smartconnect_v1_0 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_36 -libname axi_vip_v1_1_22 -libname xbip_utils_v3_0_15 -libname axi_utils_v2_0_11 -libname xbip_pipe_v3_0_11 -libname xbip_dsp48_wrapper_v3_0_7 -libname mult_gen_v12_0_24 -libname floating_point_v7_0_26 -libname div_gen_v5_1_25 -libname v_tpg_v8_2_8 -libname microblaze_v11_0_16 -libname lmb_v10_v3_0_16 -libname lmb_bram_if_cntlr_v4_0_27 -libname blk_mem_gen_v8_4_12 -libname axi_intc_v4_1_22 -libname mdm_v3_2_29 -libname interrupt_control_v3_1_5 -libname axi_iic_v2_1_11 -libname gtwizard_ultrascale_v1_7_22 -libname vid_phy_controller_v2_2_22 -libname xlconstant_v1_1_10 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm v_hdmi_tx_v3_0_6 xil_defaultlib axi_lite_ipif_v3_0_4 v_tc_v6_2_11 v_tc_v6_1_14 v_vid_in_axi4s_v4_0_11 v_axi4s_vid_out_v4_0_20 proc_sys_reset_v5_0_17 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_36 axi_vip_v1_1_22 xbip_utils_v3_0_15 axi_utils_v2_0_11 xbip_pipe_v3_0_11 xbip_dsp48_wrapper_v3_0_7 mult_gen_v12_0_24 floating_point_v7_0_26 div_gen_v5_1_25 v_tpg_v8_2_8 microblaze_v11_0_16 lmb_v10_v3_0_16 lmb_bram_if_cntlr_v4_0_27 blk_mem_gen_v8_4_12 axi_intc_v4_1_22 mdm_v3_2_29 interrupt_control_v3_1_5 axi_iic_v2_1_11 gtwizard_ultrascale_v1_7_22 vid_phy_controller_v2_2_22 xlconstant_v1_1_10)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "hdmi_tx_bd.sh - Script generated by export_simulation (Vivado v2025.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./hdmi_tx_bd.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "/home/dan-alencar/2025.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/home/dan-alencar/2025.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/home/dan-alencar/2025.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/home/dan-alencar/2025.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/home/dan-alencar/2025.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/home/dan-alencar/2025.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/home/dan-alencar/2025.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/home/dan-alencar/2025.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/home/dan-alencar/2025.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "/home/dan-alencar/2025.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/home/dan-alencar/2025.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/home/dan-alencar/2025.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/home/dan-alencar/2025.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work v_hdmi_tx_v3_0_6 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/1ccc/hdl/v_hdmi_tx_v3_0_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_0/ip/ip_0/sim/bd_2339_v_hdmi_tx_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_2_11 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/c219/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_0/ip/ip_1/sim/bd_2339_v_tc_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_1_14 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/fd54/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_vid_in_axi4s_v4_0_11 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/4705/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_axi4s_vid_out_v4_0_20 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/d1ca/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_0/ip/ip_2/sim/bd_2339_v_axi4s_vid_out_0.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/sim/bd_6eeb.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_17 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_1/sim/bd_6eeb_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/0848/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_2/sim/bd_6eeb_arinsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_3/sim/bd_6eeb_rinsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_4/sim/bd_6eeb_awinsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_5/sim/bd_6eeb_winsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_6/sim/bd_6eeb_binsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_7/sim/bd_6eeb_aroutsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_8/sim/bd_6eeb_routsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_9/sim/bd_6eeb_awoutsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_10/sim/bd_6eeb_woutsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_11/sim/bd_6eeb_boutsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_12/sim/bd_6eeb_arni_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_13/sim/bd_6eeb_rni_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_14/sim/bd_6eeb_awni_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_15/sim/bd_6eeb_wni_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_16/sim/bd_6eeb_bni_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/3d9a/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_17/sim/bd_6eeb_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/7785/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_18/sim/bd_6eeb_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/3051/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_19/sim/bd_6eeb_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/852f/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_20/sim/bd_6eeb_s00a2s_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_21/sim/bd_6eeb_sarn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_22/sim/bd_6eeb_srn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_23/sim/bd_6eeb_sawn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_24/sim/bd_6eeb_swn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_25/sim/bd_6eeb_sbn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/fca9/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_26/sim/bd_6eeb_m00s2a_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_27/sim/bd_6eeb_m00arn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_28/sim/bd_6eeb_m00rn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_29/sim/bd_6eeb_m00awn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_30/sim/bd_6eeb_m00wn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_31/sim/bd_6eeb_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/e44a/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_32/sim/bd_6eeb_m00e_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_33/sim/bd_6eeb_m01s2a_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_34/sim/bd_6eeb_m01arn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_35/sim/bd_6eeb_m01rn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_36/sim/bd_6eeb_m01awn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_37/sim/bd_6eeb_m01wn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_38/sim/bd_6eeb_m01bn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_1/ip/ip_39/sim/bd_6eeb_m01e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work smartconnect_v1_0 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_36 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/bc4b/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_22 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/b16a/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_0/ip/ip_4/sim/bd_2339_axi_smartconnect_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/bd_0/sim/bd_2339.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_tx_ss_0_0/sim/hdmi_tx_bd_v_hdmi_tx_ss_0_0.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_CTRL_s_axi.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_fifo_w96_d16_A.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_flow_control_loop_pipe_sequential_init.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_hls_deadlock_detection_unit.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_hls_deadlock_idx0_monitor.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mac_muladd_8ns_5ns_16ns_17_4_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mac_muladd_8ns_6s_15ns_16_4_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mac_muladd_8ns_7ns_13ns_15_4_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mac_muladd_8ns_7s_16s_16_4_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mac_muladd_8ns_8ns_15ns_16_4_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mac_muladd_8ns_8s_16s_16_4_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mac_muladd_16s_16s_16s_16_4_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mul_11ns_13ns_23_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mul_17s_17ns_32_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_mul_20s_9ns_28_2_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_MultiPixStream2AXIvideo.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_reg_ap_uint_10_s.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_reg_int_s.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_reg_unsigned_short_s.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_regslice_both.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_7_2_96_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_7_16_8_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_9_3_8_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_15_3_9_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_17_3_1_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_17_3_6_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_17_3_8_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_33_4_3_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_49_5_2_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_sparsemux_129_6_3_1_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_start_for_MultiPixStream2AXIvideo_U0.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_start_for_tpgForeground_U0.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_blkYuv_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_bluYuv_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_grnYuv_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_0_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_1_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_2_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_3_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_4_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_5_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_6_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_redYuv_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgBackground_whiYuv_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgForeground.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_tpgForeground_whiYuv_2_ROM_AUTO_1R.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_urem_11ns_4ns_3_15_1.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_v_tpgHlsDataFlow.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog/hdmi_tx_bd_v_tpg_0_0_v_tpg.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xbip_utils_v3_0_15 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_utils_v2_0_11 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_pipe_v3_0_11 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_wrapper_v3_0_7 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mult_gen_v12_0_24 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work floating_point_v7_0_26 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work div_gen_v5_1_25 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_tpg_v8_2_8 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/v_tpg_v8_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/sim/hdmi_tx_bd_v_tpg_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work microblaze_v11_0_16 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/c957/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_0/sim/hdmi_tx_bd_microblaze_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_v10_v3_0_16 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/dac4/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_dlmb_v10_0/sim/hdmi_tx_bd_dlmb_v10_0.vhd" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_ilmb_v10_0/sim/hdmi_tx_bd_ilmb_v10_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_bram_if_cntlr_v4_0_27 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/7cd0/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_dlmb_bram_if_cntlr_0/sim/hdmi_tx_bd_dlmb_bram_if_cntlr_0.vhd" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_ilmb_bram_if_cntlr_0/sim/hdmi_tx_bd_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_12 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/42f3/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_lmb_bram_0/sim/hdmi_tx_bd_lmb_bram_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_1/sim/bd_5bc6_psr0_0.vhd" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_2/sim/bd_5bc6_psr_aclk_0.vhd" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_3/sim/bd_5bc6_psr_aclk1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_4/sim/bd_5bc6_arinsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_5/sim/bd_5bc6_rinsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_6/sim/bd_5bc6_awinsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_7/sim/bd_5bc6_winsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_8/sim/bd_5bc6_binsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_9/sim/bd_5bc6_aroutsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_10/sim/bd_5bc6_routsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_11/sim/bd_5bc6_awoutsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_12/sim/bd_5bc6_woutsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_13/sim/bd_5bc6_boutsw_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_14/sim/bd_5bc6_arni_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_15/sim/bd_5bc6_rni_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_16/sim/bd_5bc6_awni_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_17/sim/bd_5bc6_wni_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_18/sim/bd_5bc6_bni_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_19/sim/bd_5bc6_s00mmu_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_20/sim/bd_5bc6_s00tr_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_21/sim/bd_5bc6_s00sic_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_22/sim/bd_5bc6_s00a2s_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_23/sim/bd_5bc6_sarn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_24/sim/bd_5bc6_srn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_25/sim/bd_5bc6_sawn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_26/sim/bd_5bc6_swn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_27/sim/bd_5bc6_sbn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_28/sim/bd_5bc6_m00s2a_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_29/sim/bd_5bc6_m00arn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_30/sim/bd_5bc6_m00rn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_31/sim/bd_5bc6_m00awn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_32/sim/bd_5bc6_m00wn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_33/sim/bd_5bc6_m00bn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_34/sim/bd_5bc6_m00e_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_35/sim/bd_5bc6_m01s2a_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_36/sim/bd_5bc6_m01arn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_37/sim/bd_5bc6_m01rn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_38/sim/bd_5bc6_m01awn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_39/sim/bd_5bc6_m01wn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_40/sim/bd_5bc6_m01bn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_41/sim/bd_5bc6_m01e_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_42/sim/bd_5bc6_m02s2a_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_43/sim/bd_5bc6_m02arn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_44/sim/bd_5bc6_m02rn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_45/sim/bd_5bc6_m02awn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_46/sim/bd_5bc6_m02wn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_47/sim/bd_5bc6_m02bn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_48/sim/bd_5bc6_m02e_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_49/sim/bd_5bc6_m03s2a_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_50/sim/bd_5bc6_m03arn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_51/sim/bd_5bc6_m03rn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_52/sim/bd_5bc6_m03awn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_53/sim/bd_5bc6_m03wn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_54/sim/bd_5bc6_m03bn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_55/sim/bd_5bc6_m03e_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_56/sim/bd_5bc6_m04s2a_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_57/sim/bd_5bc6_m04arn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_58/sim/bd_5bc6_m04rn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_59/sim/bd_5bc6_m04awn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_60/sim/bd_5bc6_m04wn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_61/sim/bd_5bc6_m04bn_0.sv" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/ip/ip_62/sim/bd_5bc6_m04e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/bd_0/sim/bd_5bc6.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_periph_0/sim/hdmi_tx_bd_microblaze_0_axi_periph_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_intc_v4_1_22 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f258/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_axi_intc_0/sim/hdmi_tx_bd_microblaze_0_axi_intc_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mdm_v3_2_29 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/1dd0/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_mdm_1_0/sim/hdmi_tx_bd_mdm_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_clk_wiz_1_0/hdmi_tx_bd_microblaze_0_clk_wiz_1_0_clk_wiz.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_microblaze_0_clk_wiz_1_0/hdmi_tx_bd_microblaze_0_clk_wiz_1_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_rst_microblaze_0_clk_wiz_1_100M_0/sim/hdmi_tx_bd_rst_microblaze_0_clk_wiz_1_100M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_5 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_iic_v2_1_11 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/67c0/hdl/axi_iic_v2_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_axi_iic_0_0/sim/hdmi_tx_bd_axi_iic_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work gtwizard_ultrascale_v1_7_22 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/5da0/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/sim/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper_gthe4_channel_wrapper.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/sim/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper_gtwizard_gthe4.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/sim/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper_gtwizard_top.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/ip_0/sim/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work vid_phy_controller_v2_2_22 -V93 $xmvhdl_opts \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/vhd/nidru_20_v_7.vhd" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/vhd/bs_flex_v_2.vhd" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/vhd/nidru_20_wrapper.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work vid_phy_controller_v2_2_22 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_lib.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work vid_phy_controller_v2_2_22 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_sync_block.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_sync_pulse.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_gtxe2_hdmi_txaln.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_gtxe2_hdmi_xcvr.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work vid_phy_controller_v2_2_22 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_cpll_railing.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work vid_phy_controller_v2_2_22 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_datawidth_conv.sv" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_gt_tx_tmdsclk_patgen.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_clkdet.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work vid_phy_controller_v2_2_22 $xmvlog_opts -sv +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_dru.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work vid_phy_controller_v2_2_22 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_axi4lite.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_128_to_64_conv.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_64_to_128_conv.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_gt_usrclk_source.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_gt_usrclk_source_8series.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work vid_phy_controller_v2_2_22 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_drp_control.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_drp_control_8series.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_drp_control_hdmi.v" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_interrupts.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_CLOCK_MODULE.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_CLOCK_MODULE_8series.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_plle2_drp.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_mmcme2_drp.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_mmcme3_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work vid_phy_controller_v2_2_22 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog/vid_phy_controller_v2_2_gtp_common.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_gthe4_common.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/hdl/src/verilog/hdmi_tx_bd_vid_phy_controller_0_0_gtwrapper_gthe4_common_wrapper.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/synth/hdmi_tx_bd_vid_phy_controller_0_0_top.v" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_vid_phy_controller_0_0/sim/hdmi_tx_bd_vid_phy_controller_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_proc_sys_reset_0_0/sim/hdmi_tx_bd_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_10 $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/f0b6/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/00fe/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/ec67/hdl" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_tpg_0_0/hdl/verilog" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/a415" +incdir+"../../../../FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ipshared/6d3a/hdl/src/verilog" +incdir+"../../../../../../../../2025.2/data/rsb/busdef" +incdir+"/home/dan-alencar/2025.2/data/xilinx_vip/include" \
  "../../../bd/hdmi_tx_bd/ip/hdmi_tx_bd_xlconstant_0_0/sim/hdmi_tx_bd_xlconstant_0_0.v" \
  "../../../bd/hdmi_tx_bd/sim/hdmi_tx_bd.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.hdmi_tx_bd xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.hdmi_tx_bd -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

  # delete previous design library generated data
  if [[ ($b_clean == 1) ]]; then
    clean
    echo -e "INFO: Design library generated data deleted.\n"
    exit 0
  fi

  # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_rerun == 1) ]]; then
    # keep previous state for incremental run
    return 0
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log hdmi_tx_bd_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated design library data from the previous run
clean()
{
  files_to_remove=("${design_libs[@]}")
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="$sim_lib_dir/${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  # delete design library directory
  rm -rf $sim_lib_dir
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./hdmi_tx_bd.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -rerun)         b_rerun=1         ;;
      -reset_run)     b_reset_run=1     ;;
      -clean)         b_clean=1         ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -clean is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_clean == 1) ]]; then
    echo -e "ERROR: -clean switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: hdmi_tx_bd.sh [-help]\n\
Usage: hdmi_tx_bd.sh [-step]\n\
Usage: hdmi_tx_bd.sh [-lib_map_path]\n\
Usage: hdmi_tx_bd.sh [-rerun]\n\
Usage: hdmi_tx_bd.sh [-reset_run]\n\
Usage: hdmi_tx_bd.sh [-clean]\n\
Usage: hdmi_tx_bd.sh [-reset_log]\n\
Usage: hdmi_tx_bd.sh [-keep_index]\n\
Usage: hdmi_tx_bd.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-rerun] -- Rerun step(s) in incremental mode (data generated from the previous run will be retained).\n\
To rerun a specific step, pass the -step <name> switch in addition to -rerun switch.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-clean] -- Delete simulator generated design library data from the previous run. This switch will not\n\
execute steps defined in the script.\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_rerun=0
b_reset_run=0
b_clean=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
