# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/vid_phy_controller_0/vid_phy_controller_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vid_phy_controller_0 || ORIG_REF_NAME==vid_phy_controller_0} -quiet] -quiet
