// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module hdmi_tx_bd_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        srcYUV_dout,
        srcYUV_empty_n,
        srcYUV_read,
        srcYUV_num_data_valid,
        srcYUV_fifo_cap,
        height_val,
        width_val,
        passthruStartX_val,
        passthruStartY_val,
        passthruEndX_val,
        passthruEndY_val,
        enableInput_val,
        patternId_val,
        ZplateHorContStart_val,
        ZplateHorContDelta_val,
        ZplateVerContStart_val,
        ZplateVerContDelta_val,
        dpDynamicRange_val,
        dpYUVCoef_val,
        motionSpeed_val,
        colorFormat_val,
        bckgndYUV_din,
        bckgndYUV_full_n,
        bckgndYUV_write,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        s
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [47:0] srcYUV_dout;
input   srcYUV_empty_n;
output   srcYUV_read;
input  [4:0] srcYUV_num_data_valid;
input  [4:0] srcYUV_fifo_cap;
input  [15:0] height_val;
input  [15:0] width_val;
input  [15:0] passthruStartX_val;
input  [15:0] passthruStartY_val;
input  [15:0] passthruEndX_val;
input  [15:0] passthruEndY_val;
input  [7:0] enableInput_val;
input  [7:0] patternId_val;
input  [15:0] ZplateHorContStart_val;
input  [15:0] ZplateHorContDelta_val;
input  [15:0] ZplateVerContStart_val;
input  [15:0] ZplateVerContDelta_val;
input  [7:0] dpDynamicRange_val;
input  [7:0] dpYUVCoef_val;
input  [7:0] motionSpeed_val;
input  [7:0] colorFormat_val;
output  [47:0] bckgndYUV_din;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] rampStart;
wire   [1:0] redYuv_address0;
wire   [7:0] redYuv_q0;
wire   [1:0] grnYuv_address0;
wire   [7:0] grnYuv_q0;
wire   [1:0] bluYuv_address0;
wire   [7:0] bluYuv_q0;
wire   [1:0] blkYuv_address0;
wire   [7:0] blkYuv_q0;
wire   [1:0] whiYuv_address0;
wire   [7:0] whiYuv_q0;
wire   [1:0] whiYuv_1_address0;
wire   [7:0] whiYuv_1_q0;
wire   [1:0] blkYuv_1_address0;
wire   [7:0] blkYuv_1_q0;
reg   [15:0] rampVal_1;
reg   [7:0] rampVal;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8;
reg   [15:0] zonePlateVAddr;
reg   [2:0] vBarSel;
reg   [2:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3;
reg   [2:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2;
reg   [15:0] hdata;
reg   [7:0] vBarSel_2;
reg   [2:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3;
reg   [2:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2;
reg   [15:0] rampVal_2;
reg   [0:0] vBarSel_1;
reg   [2:0] tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3;
reg   [2:0] tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2;
reg   [7:0] colorFormat_val_read_reg_1483;
reg    ap_block_state1;
reg   [6:0] tmp_reg_1507;
reg   [7:0] motionSpeed_val_read_reg_1547;
wire    ap_CS_fsm_state2;
reg   [7:0] dpYUVCoef_val_read_reg_1552;
reg   [7:0] dpDynamicRange_val_read_reg_1557;
reg   [15:0] ZplateVerContDelta_val_read_reg_1562;
reg   [15:0] ZplateVerContStart_val_read_reg_1567;
reg   [15:0] ZplateHorContDelta_val_read_reg_1572;
reg   [15:0] ZplateHorContStart_val_read_reg_1577;
reg   [7:0] patternId_val_read_reg_1582;
reg   [7:0] enableInput_val_read_reg_1587;
reg   [15:0] passthruEndY_val_read_reg_1592;
reg   [15:0] passthruEndX_val_read_reg_1597;
reg   [15:0] passthruStartY_val_read_reg_1603;
reg   [15:0] passthruStartX_val_read_reg_1608;
reg   [15:0] width_val_read_reg_1614;
reg   [15:0] height_val_read_reg_1619;
reg   [7:0] rampStart_load_reg_1624;
wire   [7:0] select_ln1122_fu_1064_p3;
reg   [7:0] select_ln1122_reg_1630;
reg   [10:0] barWidth_reg_1635;
wire   [7:0] trunc_ln1247_fu_1092_p1;
reg   [7:0] trunc_ln1247_reg_1640;
wire   [9:0] add_ln1373_1_fu_1112_p2;
reg   [9:0] add_ln1373_1_reg_1645;
wire   [15:0] shl_ln_fu_1124_p3;
reg   [15:0] shl_ln_reg_1650;
wire   [10:0] add_ln1386_fu_1146_p2;
reg   [10:0] add_ln1386_reg_1655;
wire   [16:0] add_ln1473_fu_1152_p2;
reg   [16:0] add_ln1473_reg_1660;
wire   [16:0] add_ln1449_fu_1158_p2;
reg   [16:0] add_ln1449_reg_1665;
wire   [7:0] select_ln1503_fu_1164_p3;
reg   [7:0] select_ln1503_reg_1670;
wire   [7:0] select_ln1518_fu_1172_p3;
reg   [7:0] select_ln1518_reg_1675;
reg   [7:0] redYuv_load_reg_1680;
reg   [7:0] grnYuv_load_reg_1685;
reg   [7:0] bluYuv_load_reg_1690;
reg   [7:0] blkYuv_load_reg_1695;
reg   [7:0] whiYuv_load_reg_1700;
reg   [7:0] whiYuv_1_load_reg_1705;
reg   [7:0] blkYuv_1_load_reg_1710;
reg   [15:0] y_3_reg_1715;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln736_fu_1199_p2;
reg   [0:0] icmp_ln736_reg_1723;
wire   [0:0] xor_ln737_fu_1210_p2;
reg   [0:0] xor_ln737_reg_1728;
wire   [0:0] icmp_ln1337_fu_1217_p2;
reg   [0:0] icmp_ln1337_reg_1733;
wire   [0:0] icmp_ln1449_fu_1224_p2;
reg   [0:0] icmp_ln1449_reg_1738;
wire   [7:0] add_ln1533_fu_1234_p2;
reg   [7:0] add_ln1533_reg_1743;
reg   [1:0] Sel_reg_1748;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_ready;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_srcYUV_read;
wire   [47:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_bckgndYUV_write;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_3_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_3_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_8_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_8_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_9_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_9_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_11_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_11_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_10_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_10_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_9_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_9_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_8_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_8_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_7_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_7_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_6_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_6_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0_1378_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0_1378_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09_1376_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09_1376_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010_1374_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010_1374_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0372_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0372_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09370_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09370_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010368_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010368_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_1_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_589_p4;
reg   [0:0] rampVal_3_flag_0_reg_585;
wire    ap_CS_fsm_state5;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_601_p4;
reg   [0:0] hdata_flag_0_reg_597;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_613_p4;
reg   [0:0] rampVal_2_flag_0_reg_609;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_start_reg;
wire   [0:0] icmp_ln563_fu_1184_p2;
wire    ap_CS_fsm_state4;
reg   [15:0] rampVal_3_new_0_fu_382;
reg   [15:0] rampVal_3_loc_0_fu_378;
reg   [15:0] rampVal_loc_0_fu_374;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_370;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_2_fu_366;
reg   [15:0] zonePlateVAddr_loc_0_fu_362;
reg   [7:0] vBarSel_loc_0_fu_358;
reg   [7:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_354;
reg   [7:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_350;
reg   [15:0] hdata_new_0_fu_346;
reg   [15:0] hdata_loc_0_fu_342;
reg   [7:0] vBarSel_2_loc_0_fu_338;
reg   [7:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_334;
reg   [7:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_330;
reg   [15:0] rampVal_2_new_0_fu_326;
reg   [15:0] rampVal_2_loc_0_fu_322;
reg   [7:0] vBarSel_3_loc_0_fu_318;
reg   [7:0] tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_6_fu_314;
reg   [7:0] tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_7_fu_310;
reg   [7:0] outpix_5_fu_302;
reg   [7:0] outpix_4_fu_298;
reg   [7:0] outpix_3_fu_294;
reg   [7:0] outpix_2_fu_290;
reg   [7:0] outpix_1_fu_286;
reg   [7:0] outpix_fu_282;
reg   [7:0] p_0_0_0_1379_lcssa397_fu_278;
reg   [7:0] p_0_0_09_1377_lcssa394_fu_274;
reg   [7:0] p_0_0_010_1375_lcssa391_fu_270;
reg   [7:0] p_0_0_0373_lcssa388_fu_266;
reg   [7:0] p_0_0_09371_lcssa385_fu_262;
reg   [7:0] p_0_0_010369_lcssa382_fu_258;
wire   [63:0] select_ln1144_fu_839_p3;
wire   [7:0] add_ln750_fu_1256_p2;
reg   [15:0] y_fu_306;
wire   [15:0] add_ln563_fu_1189_p2;
wire   [7:0] zext_ln563_fu_950_p1;
wire   [7:0] zext_ln1775_1_fu_942_p1;
wire   [7:0] zext_ln1775_fu_934_p1;
wire   [7:0] zext_ln1664_fu_922_p1;
wire   [7:0] zext_ln1593_fu_914_p1;
wire   [7:0] zext_ln1545_fu_898_p1;
wire   [7:0] zext_ln1412_1_fu_890_p1;
wire   [7:0] zext_ln1412_fu_882_p1;
wire   [15:0] zext_ln1257_fu_862_p1;
reg    redYuv_ce0_local;
reg    grnYuv_ce0_local;
reg    bluYuv_ce0_local;
reg    blkYuv_ce0_local;
reg    whiYuv_ce0_local;
reg    whiYuv_1_ce0_local;
reg    blkYuv_1_ce0_local;
wire   [0:0] icmp_ln1144_fu_823_p2;
wire   [0:0] icmp_ln1122_fu_1047_p2;
wire   [13:0] trunc_ln1122_fu_1043_p1;
wire   [13:0] add_ln1241_fu_1076_p2;
wire   [13:0] add_ln1373_fu_1096_p2;
wire   [9:0] trunc_ln5_fu_1102_p4;
wire   [13:0] trunc_ln1120_fu_1056_p1;
wire   [13:0] add_ln1374_fu_1118_p2;
wire   [9:0] tmp_2_fu_1132_p4;
wire   [10:0] zext_ln1386_fu_1142_p1;
wire   [16:0] zext_ln1122_fu_1039_p1;
wire   [16:0] zext_ln1120_fu_1052_p1;
wire   [0:0] icmp_ln737_fu_1205_p2;
wire   [16:0] zext_ln563_1_fu_1195_p1;
wire   [7:0] trunc_ln1533_fu_1230_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 rampStart = 8'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 8'd0;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel = 8'd0;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8 = 8'd0;
#0 zonePlateVAddr = 16'd0;
#0 vBarSel = 3'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3 = 3'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2 = 3'd0;
#0 hdata = 16'd0;
#0 vBarSel_2 = 8'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3 = 3'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2 = 3'd0;
#0 rampVal_2 = 16'd0;
#0 vBarSel_1 = 1'd0;
#0 tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3 = 3'd0;
#0 tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2 = 3'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_start_reg = 1'b0;
#0 rampVal_3_loc_0_fu_378 = 16'd0;
#0 rampVal_loc_0_fu_374 = 16'd0;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_370 = 8'd0;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_2_fu_366 = 8'd0;
#0 zonePlateVAddr_loc_0_fu_362 = 16'd0;
#0 vBarSel_loc_0_fu_358 = 8'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_354 = 8'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_350 = 8'd0;
#0 hdata_loc_0_fu_342 = 16'd0;
#0 vBarSel_2_loc_0_fu_338 = 8'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_334 = 8'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_330 = 8'd0;
#0 rampVal_2_loc_0_fu_322 = 16'd0;
#0 vBarSel_3_loc_0_fu_318 = 8'd0;
#0 tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_6_fu_314 = 8'd0;
#0 tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_7_fu_310 = 8'd0;
#0 y_fu_306 = 16'd0;
end

hdmi_tx_bd_v_tpg_0_0_tpgBackground_redYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
redYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(redYuv_address0),
    .ce0(redYuv_ce0_local),
    .q0(redYuv_q0)
);

hdmi_tx_bd_v_tpg_0_0_tpgBackground_grnYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
grnYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grnYuv_address0),
    .ce0(grnYuv_ce0_local),
    .q0(grnYuv_q0)
);

hdmi_tx_bd_v_tpg_0_0_tpgBackground_bluYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
bluYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bluYuv_address0),
    .ce0(bluYuv_ce0_local),
    .q0(bluYuv_q0)
);

hdmi_tx_bd_v_tpg_0_0_tpgBackground_blkYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
blkYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blkYuv_address0),
    .ce0(blkYuv_ce0_local),
    .q0(blkYuv_q0)
);

hdmi_tx_bd_v_tpg_0_0_tpgBackground_whiYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_address0),
    .ce0(whiYuv_ce0_local),
    .q0(whiYuv_q0)
);

hdmi_tx_bd_v_tpg_0_0_tpgBackground_whiYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_1_address0),
    .ce0(whiYuv_1_ce0_local),
    .q0(whiYuv_1_q0)
);

hdmi_tx_bd_v_tpg_0_0_tpgBackground_blkYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
blkYuv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blkYuv_1_address0),
    .ce0(blkYuv_1_ce0_local),
    .q0(blkYuv_1_q0)
);

hdmi_tx_bd_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_ready),
    .srcYUV_dout(srcYUV_dout),
    .srcYUV_empty_n(srcYUV_empty_n),
    .srcYUV_read(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_srcYUV_read),
    .srcYUV_num_data_valid(5'd0),
    .srcYUV_fifo_cap(5'd0),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_bckgndYUV_din),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_bckgndYUV_write),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_585),
    .hdata_flag_0(hdata_flag_0_reg_597),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_609),
    .dpDynamicRange_val(dpDynamicRange_val_read_reg_1557),
    .colorFormat_val(colorFormat_val_read_reg_1483),
    .dpYUVCoef_val(dpYUVCoef_val_read_reg_1552),
    .empty_46(tmp_reg_1507),
    .Sel(Sel_reg_1748),
    .y(y_3_reg_1715),
    .barWidth(barWidth_reg_1635),
    .enableInput_val(enableInput_val_read_reg_1587),
    .width_val(width_val_read_reg_1614),
    .outpix_24(select_ln1122_reg_1630),
    .select_ln1518(select_ln1518_reg_1675),
    .select_ln1503(select_ln1503_reg_1670),
    .rampStart_1(rampStart_load_reg_1624),
    .zext_ln736(passthruStartX_val_read_reg_1608),
    .zext_ln563(passthruEndX_val_read_reg_1597),
    .rev(xor_ln737_reg_1728),
    .icmp_ln736(icmp_ln736_reg_1723),
    .passthruStartX_val(passthruStartX_val_read_reg_1608),
    .passthruEndX_val(passthruEndX_val_read_reg_1597),
    .patternId_val(patternId_val_read_reg_1582),
    .zext_ln1120_1(rampStart_load_reg_1624),
    .redYuv_load(redYuv_load_reg_1680),
    .grnYuv_load(grnYuv_load_reg_1685),
    .bluYuv_load(bluYuv_load_reg_1690),
    .blkYuv_load(blkYuv_load_reg_1695),
    .whiYuv_load(whiYuv_load_reg_1700),
    .empty(trunc_ln1247_reg_1640),
    .shl_ln(shl_ln_reg_1650),
    .ZplateHorContStart_val(ZplateHorContStart_val_read_reg_1577),
    .ZplateHorContDelta_val(ZplateHorContDelta_val_read_reg_1572),
    .ZplateVerContStart_val(ZplateVerContStart_val_read_reg_1567),
    .icmp_ln1337(icmp_ln1337_reg_1733),
    .ZplateVerContDelta_val(ZplateVerContDelta_val_read_reg_1562),
    .barWidthMinSamples(add_ln1373_1_reg_1645),
    .add_ln1386(add_ln1386_reg_1655),
    .blkYuv_1_load(blkYuv_1_load_reg_1710),
    .add_ln1473(add_ln1473_reg_1660),
    .icmp_ln1449_1(icmp_ln1449_reg_1738),
    .whiYuv_3_load(whiYuv_1_load_reg_1705),
    .add_ln1533(add_ln1533_reg_1743),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_378),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_374),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_loc_1_out_o_ap_vld),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_i(tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_370),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_3_out_i(tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_2_fu_366),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_3_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_3_out_o),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_3_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_3_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_362),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr_loc_1_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_358),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_loc_1_out_o_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_i(tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_354),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_i(tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_350),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_342),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_loc_1_out_o_ap_vld),
    .vBarSel_2_loc_1_out_i(vBarSel_2_loc_0_fu_338),
    .vBarSel_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2_loc_1_out_o),
    .vBarSel_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2_loc_1_out_o_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_i(tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_334),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_i(tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_330),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_322),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_loc_1_out_o_ap_vld),
    .vBarSel_3_loc_1_out_i(vBarSel_3_loc_0_fu_318),
    .vBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_3_loc_1_out_o),
    .vBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_3_loc_1_out_o_ap_vld),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_8_out_i(tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_6_fu_314),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_8_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_8_out_o),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_8_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_8_out_o_ap_vld),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_9_out_i(tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_7_fu_310),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_9_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_9_out_o),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_9_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_9_out_o_ap_vld),
    .outpix_11_out_i(outpix_5_fu_302),
    .outpix_11_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_11_out_o),
    .outpix_11_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_11_out_o_ap_vld),
    .outpix_10_out_i(outpix_4_fu_298),
    .outpix_10_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_10_out_o),
    .outpix_10_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_10_out_o_ap_vld),
    .outpix_9_out_i(outpix_3_fu_294),
    .outpix_9_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_9_out_o),
    .outpix_9_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_9_out_o_ap_vld),
    .outpix_8_out_i(outpix_2_fu_290),
    .outpix_8_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_8_out_o),
    .outpix_8_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_8_out_o_ap_vld),
    .outpix_7_out_i(outpix_1_fu_286),
    .outpix_7_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_7_out_o),
    .outpix_7_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_7_out_o_ap_vld),
    .outpix_6_out_i(outpix_fu_282),
    .outpix_6_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_6_out_o),
    .outpix_6_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_6_out_o_ap_vld),
    .p_0_0_0_1378_out_i(p_0_0_0_1379_lcssa397_fu_278),
    .p_0_0_0_1378_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0_1378_out_o),
    .p_0_0_0_1378_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0_1378_out_o_ap_vld),
    .p_0_0_09_1376_out_i(p_0_0_09_1377_lcssa394_fu_274),
    .p_0_0_09_1376_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09_1376_out_o),
    .p_0_0_09_1376_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09_1376_out_o_ap_vld),
    .p_0_0_010_1374_out_i(p_0_0_010_1375_lcssa391_fu_270),
    .p_0_0_010_1374_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010_1374_out_o),
    .p_0_0_010_1374_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010_1374_out_o_ap_vld),
    .p_0_0_0372_out_i(p_0_0_0373_lcssa388_fu_266),
    .p_0_0_0372_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0372_out_o),
    .p_0_0_0372_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0372_out_o_ap_vld),
    .p_0_0_09370_out_i(p_0_0_09371_lcssa385_fu_262),
    .p_0_0_09370_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09370_out_o),
    .p_0_0_09370_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09370_out_o_ap_vld),
    .p_0_0_010368_out_i(p_0_0_010369_lcssa382_fu_258),
    .p_0_0_010368_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010368_out_o),
    .p_0_0_010368_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010368_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_ap_vld),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_ap_vld),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_ap_vld),
    .vBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2),
    .vBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2_ap_vld),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2_ap_vld),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln563_fu_1184_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln563_fu_1184_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hdata_flag_0_reg_597 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_flag_1_out;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hdata_flag_0_reg_597 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hdata_loc_0_fu_342 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_loc_0_fu_342 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_2_flag_0_reg_609 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_flag_1_out;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rampVal_2_flag_0_reg_609 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_2_loc_0_fu_322 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_loc_0_fu_322 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_3_flag_0_reg_585 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_flag_1_out;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rampVal_3_flag_0_reg_585 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_3_loc_0_fu_378 <= rampVal_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_3_loc_0_fu_378 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_loc_0_fu_374 <= zext_ln1257_fu_862_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_loc_0_fu_374 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_334 <= zext_ln1593_fu_914_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_334 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_330 <= zext_ln1664_fu_922_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_330 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_2_fu_366 <= tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_3_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_2_fu_366 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_3_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_370 <= tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_370 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_6_fu_314 <= zext_ln1775_1_fu_942_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_8_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_6_fu_314 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_8_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_7_fu_310 <= zext_ln563_fu_950_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_9_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_7_fu_310 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_9_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_354 <= zext_ln1412_1_fu_890_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_354 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_350 <= zext_ln1545_fu_898_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_350 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_2_loc_0_fu_338 <= vBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_2_loc_0_fu_338 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_3_loc_0_fu_318 <= zext_ln1775_fu_934_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_3_loc_0_fu_318 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_loc_0_fu_358 <= zext_ln1412_fu_882_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_loc_0_fu_358 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        y_fu_306 <= 16'd0;
    end else if (((icmp_ln563_fu_1184_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        y_fu_306 <= add_ln563_fu_1189_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        zonePlateVAddr_loc_0_fu_362 <= zonePlateVAddr;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr_loc_0_fu_362 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Sel_reg_1748 <= {{y_fu_306[7:6]}};
        add_ln1533_reg_1743 <= add_ln1533_fu_1234_p2;
        icmp_ln1337_reg_1733 <= icmp_ln1337_fu_1217_p2;
        icmp_ln1449_reg_1738 <= icmp_ln1449_fu_1224_p2;
        icmp_ln736_reg_1723 <= icmp_ln736_fu_1199_p2;
        xor_ln737_reg_1728 <= xor_ln737_fu_1210_p2;
        y_3_reg_1715 <= y_fu_306;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ZplateHorContDelta_val_read_reg_1572 <= ZplateHorContDelta_val;
        ZplateHorContStart_val_read_reg_1577 <= ZplateHorContStart_val;
        ZplateVerContDelta_val_read_reg_1562 <= ZplateVerContDelta_val;
        ZplateVerContStart_val_read_reg_1567 <= ZplateVerContStart_val;
        add_ln1373_1_reg_1645 <= add_ln1373_1_fu_1112_p2;
        add_ln1386_reg_1655 <= add_ln1386_fu_1146_p2;
        add_ln1449_reg_1665 <= add_ln1449_fu_1158_p2;
        add_ln1473_reg_1660 <= add_ln1473_fu_1152_p2;
        barWidth_reg_1635 <= {{add_ln1241_fu_1076_p2[13:3]}};
        blkYuv_1_load_reg_1710 <= blkYuv_1_q0;
        blkYuv_load_reg_1695 <= blkYuv_q0;
        bluYuv_load_reg_1690 <= bluYuv_q0;
        dpDynamicRange_val_read_reg_1557 <= dpDynamicRange_val;
        dpYUVCoef_val_read_reg_1552 <= dpYUVCoef_val;
        enableInput_val_read_reg_1587 <= enableInput_val;
        grnYuv_load_reg_1685 <= grnYuv_q0;
        height_val_read_reg_1619 <= height_val;
        motionSpeed_val_read_reg_1547 <= motionSpeed_val;
        passthruEndX_val_read_reg_1597 <= passthruEndX_val;
        passthruEndY_val_read_reg_1592 <= passthruEndY_val;
        passthruStartX_val_read_reg_1608 <= passthruStartX_val;
        passthruStartY_val_read_reg_1603 <= passthruStartY_val;
        patternId_val_read_reg_1582 <= patternId_val;
        rampStart_load_reg_1624 <= rampStart;
        redYuv_load_reg_1680 <= redYuv_q0;
        select_ln1122_reg_1630 <= select_ln1122_fu_1064_p3;
        select_ln1503_reg_1670[6 : 0] <= select_ln1503_fu_1164_p3[6 : 0];
        select_ln1518_reg_1675[7] <= select_ln1518_fu_1172_p3[7];
        shl_ln_reg_1650[15 : 8] <= shl_ln_fu_1124_p3[15 : 8];
        trunc_ln1247_reg_1640 <= trunc_ln1247_fu_1092_p1;
        whiYuv_1_load_reg_1705 <= whiYuv_1_q0;
        whiYuv_load_reg_1700 <= whiYuv_q0;
        width_val_read_reg_1614 <= width_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        colorFormat_val_read_reg_1483 <= colorFormat_val;
        tmp_reg_1507 <= {{colorFormat_val[7:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1184_p2 == 1'd1) & (ap_phi_mux_hdata_flag_0_phi_fu_601_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata <= hdata_new_0_fu_346;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_new_0_fu_346 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_7_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_1_fu_286 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_7_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_8_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_2_fu_290 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_8_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_9_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_3_fu_294 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_9_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_10_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_4_fu_298 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_10_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_11_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_5_fu_302 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_11_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_6_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_fu_282 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_outpix_6_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010368_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_010369_lcssa382_fu_258 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010368_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010_1374_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_010_1375_lcssa391_fu_270 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_010_1374_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0372_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0373_lcssa388_fu_266 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0372_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09370_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_09371_lcssa385_fu_262 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09370_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09_1376_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_09_1377_lcssa394_fu_274 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_09_1376_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0_1378_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_1379_lcssa397_fu_278 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_p_0_0_0_1378_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1184_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampStart <= add_ln750_fu_1256_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1184_p2 == 1'd1) & (ap_phi_mux_rampVal_3_flag_0_phi_fu_589_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_1 <= rampVal_3_new_0_fu_382;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1184_p2 == 1'd1) & (ap_phi_mux_rampVal_2_flag_0_phi_fu_613_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2 <= rampVal_2_new_0_fu_326;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_new_0_fu_326 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_3_new_0_fu_382 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_8;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_vBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_zonePlateVAddr;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln563_fu_1184_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        blkYuv_1_ce0_local = 1'b1;
    end else begin
        blkYuv_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        blkYuv_ce0_local = 1'b1;
    end else begin
        blkYuv_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        bluYuv_ce0_local = 1'b1;
    end else begin
        bluYuv_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        grnYuv_ce0_local = 1'b1;
    end else begin
        grnYuv_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln563_fu_1184_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        redYuv_ce0_local = 1'b1;
    end else begin
        redYuv_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        whiYuv_1_ce0_local = 1'b1;
    end else begin
        whiYuv_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        whiYuv_ce0_local = 1'b1;
    end else begin
        whiYuv_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln563_fu_1184_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1241_fu_1076_p2 = (trunc_ln1122_fu_1043_p1 + 14'd7);

assign add_ln1373_1_fu_1112_p2 = ($signed(trunc_ln5_fu_1102_p4) + $signed(10'd1022));

assign add_ln1373_fu_1096_p2 = (trunc_ln1122_fu_1043_p1 + 14'd15);

assign add_ln1374_fu_1118_p2 = (trunc_ln1120_fu_1056_p1 + 14'd15);

assign add_ln1386_fu_1146_p2 = ($signed(zext_ln1386_fu_1142_p1) + $signed(11'd2047));

assign add_ln1449_fu_1158_p2 = ($signed(zext_ln1120_fu_1052_p1) + $signed(17'd131071));

assign add_ln1473_fu_1152_p2 = ($signed(zext_ln1122_fu_1039_p1) + $signed(17'd131071));

assign add_ln1533_fu_1234_p2 = (rampStart + trunc_ln1533_fu_1230_p1);

assign add_ln563_fu_1189_p2 = (y_fu_306 + 16'd1);

assign add_ln750_fu_1256_p2 = (rampStart + motionSpeed_val_read_reg_1547);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_601_p4 = hdata_flag_0_reg_597;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_613_p4 = rampVal_2_flag_0_reg_609;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_589_p4 = rampVal_3_flag_0_reg_585;

assign ap_ready = internal_ap_ready;

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_bckgndYUV_din;

assign bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_bckgndYUV_write;

assign blkYuv_1_address0 = select_ln1144_fu_839_p3;

assign blkYuv_address0 = select_ln1144_fu_839_p3;

assign bluYuv_address0 = select_ln1144_fu_839_p3;

assign grnYuv_address0 = select_ln1144_fu_839_p3;

assign grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_ap_start_reg;

assign icmp_ln1122_fu_1047_p2 = ((colorFormat_val_read_reg_1483 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln1144_fu_823_p2 = ((colorFormat_val == 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln1337_fu_1217_p2 = ((y_fu_306 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1449_fu_1224_p2 = ((add_ln1449_reg_1665 == zext_ln563_1_fu_1195_p1) ? 1'b1 : 1'b0);

assign icmp_ln563_fu_1184_p2 = ((y_fu_306 == height_val_read_reg_1619) ? 1'b1 : 1'b0);

assign icmp_ln736_fu_1199_p2 = ((y_fu_306 < passthruStartY_val_read_reg_1603) ? 1'b1 : 1'b0);

assign icmp_ln737_fu_1205_p2 = ((y_fu_306 < passthruEndY_val_read_reg_1592) ? 1'b1 : 1'b0);

assign redYuv_address0 = select_ln1144_fu_839_p3;

assign select_ln1122_fu_1064_p3 = ((icmp_ln1122_fu_1047_p2[0:0] == 1'b1) ? rampStart : 8'd128);

assign select_ln1144_fu_839_p3 = ((icmp_ln1144_fu_823_p2[0:0] == 1'b1) ? 64'd1 : 64'd2);

assign select_ln1503_fu_1164_p3 = ((icmp_ln1122_fu_1047_p2[0:0] == 1'b1) ? 8'd255 : 8'd128);

assign select_ln1518_fu_1172_p3 = ((icmp_ln1122_fu_1047_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign shl_ln_fu_1124_p3 = {{rampStart}, {8'd0}};

assign srcYUV_read = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_621_srcYUV_read;

assign start_out = real_start;

assign tmp_2_fu_1132_p4 = {{add_ln1374_fu_1118_p2[13:4]}};

assign trunc_ln1120_fu_1056_p1 = height_val[13:0];

assign trunc_ln1122_fu_1043_p1 = width_val[13:0];

assign trunc_ln1247_fu_1092_p1 = s[7:0];

assign trunc_ln1533_fu_1230_p1 = y_fu_306[7:0];

assign trunc_ln5_fu_1102_p4 = {{add_ln1373_fu_1096_p2[13:4]}};

assign whiYuv_1_address0 = select_ln1144_fu_839_p3;

assign whiYuv_address0 = select_ln1144_fu_839_p3;

assign xor_ln737_fu_1210_p2 = (icmp_ln737_fu_1205_p2 ^ 1'd1);

assign zext_ln1120_fu_1052_p1 = height_val;

assign zext_ln1122_fu_1039_p1 = width_val;

assign zext_ln1257_fu_862_p1 = rampVal;

assign zext_ln1386_fu_1142_p1 = tmp_2_fu_1132_p4;

assign zext_ln1412_1_fu_890_p1 = tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3;

assign zext_ln1412_fu_882_p1 = vBarSel;

assign zext_ln1545_fu_898_p1 = tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2;

assign zext_ln1593_fu_914_p1 = tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3;

assign zext_ln1664_fu_922_p1 = tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2;

assign zext_ln1775_1_fu_942_p1 = tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3;

assign zext_ln1775_fu_934_p1 = vBarSel_1;

assign zext_ln563_1_fu_1195_p1 = y_fu_306;

assign zext_ln563_fu_950_p1 = tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_2;

always @ (posedge ap_clk) begin
    shl_ln_reg_1650[7:0] <= 8'b00000000;
    select_ln1503_reg_1670[7] <= 1'b1;
    select_ln1518_reg_1675[6:0] <= 7'b0000000;
end

endmodule //hdmi_tx_bd_v_tpg_0_0_tpgBackground
