# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.srcs/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/hdmi_tx_bd_v_hdmi_rx_ss_0_0.xci
# IP: The module: 'hdmi_tx_bd_v_hdmi_rx_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/bd_0/bd_8312.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8312 || ORIG_REF_NAME==bd_8312} -quiet] -quiet

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/bd_0/ip/ip_0/bd_8312_v_hdmi_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8312_v_hdmi_rx_0 || ORIG_REF_NAME==bd_8312_v_hdmi_rx_0} -quiet] -quiet

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/bd_0/ip/ip_1/bd_8312_v_vid_in_axi4s_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8312_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_8312_v_vid_in_axi4s_0} -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/bd_0/bd_8312_ooc.xdc

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/hdmi_tx_bd_v_hdmi_rx_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_v_hdmi_rx_ss_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.srcs/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/hdmi_tx_bd_v_hdmi_rx_ss_0_0.xci
# IP: The module: 'hdmi_tx_bd_v_hdmi_rx_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/bd_0/bd_8312.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8312 || ORIG_REF_NAME==bd_8312} -quiet] -quiet

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/bd_0/ip/ip_0/bd_8312_v_hdmi_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8312_v_hdmi_rx_0 || ORIG_REF_NAME==bd_8312_v_hdmi_rx_0} -quiet] -quiet

# IP: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/bd_0/ip/ip_1/bd_8312_v_vid_in_axi4s_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8312_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_8312_v_vid_in_axi4s_0} -quiet] -quiet

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/bd_0/bd_8312_ooc.xdc

# XDC: /home/dan-alencar/Documents/GitHub/FPGA_PDS/FPGA_PDS/FPGA_PDS.gen/sources_1/bd/hdmi_tx_bd/ip/hdmi_tx_bd_v_hdmi_rx_ss_0_0/hdmi_tx_bd_v_hdmi_rx_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_tx_bd_v_hdmi_rx_ss_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
