// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module hdmi_tx_bd_v_tpg_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        counter_loc_0_i_i,
        sof_i,
        colorFormat_val17,
        trunc_ln_i,
        ovrlayYUV_dout,
        ovrlayYUV_empty_n,
        ovrlayYUV_read,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        add_ln994_i,
        counter_loc_1_i_i_out,
        counter_loc_1_i_i_out_ap_vld,
        phi_ln1036_i_out,
        phi_ln1036_i_out_ap_vld,
        counter,
        counter_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_state5 = 4'd4;
parameter    ap_ST_fsm_state6 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] counter_loc_0_i_i;
input  [0:0] sof_i;
input  [7:0] colorFormat_val17;
input  [8:0] trunc_ln_i;
input  [95:0] ovrlayYUV_dout;
input   ovrlayYUV_empty_n;
output   ovrlayYUV_read;
input  [4:0] ovrlayYUV_num_data_valid;
input  [4:0] ovrlayYUV_fifo_cap;
output  [95:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [11:0] m_axis_video_TKEEP;
output  [11:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [9:0] add_ln994_i;
output  [15:0] counter_loc_1_i_i_out;
output   counter_loc_1_i_i_out_ap_vld;
output  [0:0] phi_ln1036_i_out;
output   phi_ln1036_i_out_ap_vld;
output  [15:0] counter;
output   counter_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ovrlayYUV_read;
reg m_axis_video_TVALID;
reg counter_loc_1_i_i_out_ap_vld;
reg phi_ln1036_i_out_ap_vld;
reg counter_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ovrlayYUV_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln981_reg_775;
reg    m_axis_video_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln981_reg_775_pp0_iter1_reg;
reg   [0:0] sof_reg_251;
reg   [0:0] phi_ln1036_reg_264;
wire   [0:0] icmp_ln1020_fu_277_p2;
reg   [0:0] icmp_ln1020_reg_768;
wire   [0:0] icmp_ln981_fu_296_p2;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln994_fu_311_p2;
reg   [0:0] icmp_ln994_reg_779;
reg   [0:0] icmp_ln994_reg_779_pp0_iter1_reg;
wire   [95:0] tmp_i_fu_693_p9;
reg   [95:0] tmp_i_reg_784;
wire   [0:0] trunc_ln1008_fu_716_p1;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_condition_pp0_exit_iter1_state3;
reg   [0:0] ap_phi_mux_sof_phi_fu_256_p4;
wire   [15:0] add_ln1005_fu_324_p2;
reg   [8:0] j_fu_164;
wire   [8:0] j_2_fu_301_p2;
reg   [15:0] counter_loc_1_i_i_fu_168;
wire    ap_CS_fsm_state6;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state5;
wire   [9:0] zext_ln981_fu_307_p1;
wire   [7:0] pix_rgb_12_fu_345_p4;
wire   [7:0] pix_444_fu_341_p1;
wire   [7:0] pix_rgb_fu_355_p4;
wire   [7:0] tmp_174_i_i_fu_469_p4;
wire   [7:0] tmp_174_i_i_fu_469_p5;
wire   [7:0] pix_422_7_fu_365_p4;
wire   [0:0] icmp_ln1020_1_fu_484_p2;
wire   [7:0] pix_rgb_13_fu_375_p4;
wire   [7:0] tmp_176_i_i_fu_497_p2;
wire   [7:0] tmp_176_i_i_fu_497_p4;
wire   [7:0] tmp_176_i_i_fu_497_p5;
wire   [7:0] tmp_177_i_i_fu_512_p2;
wire   [7:0] tmp_177_i_i_fu_512_p4;
wire   [7:0] tmp_177_i_i_fu_512_p5;
wire   [7:0] tmp_178_i_i_fu_527_p2;
wire   [7:0] tmp_178_i_i_fu_527_p4;
wire   [7:0] tmp_178_i_i_fu_527_p5;
wire   [7:0] pix_422_10_fu_425_p4;
wire   [7:0] tmp_179_i_i_fu_542_p2;
wire   [7:0] tmp_179_i_i_fu_542_p4;
wire   [7:0] tmp_179_i_i_fu_542_p5;
wire   [7:0] tmp_180_i_i_fu_557_p2;
wire   [7:0] tmp_180_i_i_fu_557_p4;
wire   [7:0] tmp_180_i_i_fu_557_p5;
wire   [7:0] pix_422_11_fu_445_p4;
wire   [7:0] tmp_181_i_i_fu_572_p2;
wire   [7:0] tmp_181_i_i_fu_572_p4;
wire   [7:0] tmp_181_i_i_fu_572_p5;
wire   [7:0] tmp_182_i_i_fu_587_p2;
wire   [7:0] tmp_182_i_i_fu_587_p4;
wire   [7:0] tmp_182_i_i_fu_587_p5;
wire   [7:0] tmp_182_i_i_fu_587_p7;
wire   [7:0] tmp_181_i_i_fu_572_p7;
wire   [7:0] tmp_180_i_i_fu_557_p7;
wire   [7:0] tmp_179_i_i_fu_542_p7;
wire   [7:0] tmp_178_i_i_fu_527_p7;
wire   [7:0] tmp_177_i_i_fu_512_p7;
wire   [7:0] tmp_176_i_i_fu_497_p7;
wire   [7:0] pix_rgb_3_fu_489_p3;
wire   [7:0] tmp_174_i_i_fu_469_p7;
wire   [7:0] select_ln1020_1_fu_462_p3;
wire   [7:0] select_ln1020_fu_455_p3;
wire   [95:0] tmp_i_fu_693_p2;
wire   [95:0] tmp_i_fu_693_p4;
wire   [95:0] tmp_i_fu_693_p6;
wire   [95:0] tmp_i_fu_693_p7;
wire   [1:0] tmp_i_fu_693_p8;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [7:0] tmp_174_i_i_fu_469_p1;
wire   [7:0] tmp_174_i_i_fu_469_p3;
wire   [7:0] tmp_176_i_i_fu_497_p1;
wire   [7:0] tmp_176_i_i_fu_497_p3;
wire   [7:0] tmp_177_i_i_fu_512_p1;
wire   [7:0] tmp_177_i_i_fu_512_p3;
wire   [7:0] tmp_178_i_i_fu_527_p1;
wire   [7:0] tmp_178_i_i_fu_527_p3;
wire   [7:0] tmp_179_i_i_fu_542_p1;
wire   [7:0] tmp_179_i_i_fu_542_p3;
wire   [7:0] tmp_180_i_i_fu_557_p1;
wire   [7:0] tmp_180_i_i_fu_557_p3;
wire   [7:0] tmp_181_i_i_fu_572_p1;
wire   [7:0] tmp_181_i_i_fu_572_p3;
wire   [7:0] tmp_182_i_i_fu_587_p1;
wire   [7:0] tmp_182_i_i_fu_587_p3;
wire  signed [1:0] tmp_i_fu_693_p1;
wire   [1:0] tmp_i_fu_693_p3;
wire   [1:0] tmp_i_fu_693_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 j_fu_164 = 9'd0;
#0 counter_loc_1_i_i_fu_168 = 16'd0;
end

(* dissolve_hierarchy = "yes" *) hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
sparsemux_5_8_8_1_1_U405(
    .din0(pix_444_fu_341_p1),
    .din1(tmp_174_i_i_fu_469_p4),
    .def(tmp_174_i_i_fu_469_p5),
    .sel(colorFormat_val17),
    .dout(tmp_174_i_i_fu_469_p7)
);

(* dissolve_hierarchy = "yes" *) hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
sparsemux_5_8_8_1_1_U406(
    .din0(tmp_176_i_i_fu_497_p2),
    .din1(tmp_176_i_i_fu_497_p4),
    .def(tmp_176_i_i_fu_497_p5),
    .sel(colorFormat_val17),
    .dout(tmp_176_i_i_fu_497_p7)
);

(* dissolve_hierarchy = "yes" *) hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
sparsemux_5_8_8_1_1_U407(
    .din0(tmp_177_i_i_fu_512_p2),
    .din1(tmp_177_i_i_fu_512_p4),
    .def(tmp_177_i_i_fu_512_p5),
    .sel(colorFormat_val17),
    .dout(tmp_177_i_i_fu_512_p7)
);

(* dissolve_hierarchy = "yes" *) hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
sparsemux_5_8_8_1_1_U408(
    .din0(tmp_178_i_i_fu_527_p2),
    .din1(tmp_178_i_i_fu_527_p4),
    .def(tmp_178_i_i_fu_527_p5),
    .sel(colorFormat_val17),
    .dout(tmp_178_i_i_fu_527_p7)
);

(* dissolve_hierarchy = "yes" *) hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
sparsemux_5_8_8_1_1_U409(
    .din0(tmp_179_i_i_fu_542_p2),
    .din1(tmp_179_i_i_fu_542_p4),
    .def(tmp_179_i_i_fu_542_p5),
    .sel(colorFormat_val17),
    .dout(tmp_179_i_i_fu_542_p7)
);

(* dissolve_hierarchy = "yes" *) hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
sparsemux_5_8_8_1_1_U410(
    .din0(tmp_180_i_i_fu_557_p2),
    .din1(tmp_180_i_i_fu_557_p4),
    .def(tmp_180_i_i_fu_557_p5),
    .sel(colorFormat_val17),
    .dout(tmp_180_i_i_fu_557_p7)
);

(* dissolve_hierarchy = "yes" *) hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
sparsemux_5_8_8_1_1_U411(
    .din0(tmp_181_i_i_fu_572_p2),
    .din1(tmp_181_i_i_fu_572_p4),
    .def(tmp_181_i_i_fu_572_p5),
    .sel(colorFormat_val17),
    .dout(tmp_181_i_i_fu_572_p7)
);

(* dissolve_hierarchy = "yes" *) hdmi_tx_bd_v_tpg_0_0_sparsemux_5_8_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
sparsemux_5_8_8_1_1_U412(
    .din0(tmp_182_i_i_fu_587_p2),
    .din1(tmp_182_i_i_fu_587_p4),
    .def(tmp_182_i_i_fu_587_p5),
    .sel(colorFormat_val17),
    .dout(tmp_182_i_i_fu_587_p7)
);

(* dissolve_hierarchy = "yes" *) hdmi_tx_bd_v_tpg_0_0_sparsemux_7_2_96_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 96 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 96 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 96 ),
    .def_WIDTH( 96 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 96 ))
sparsemux_7_2_96_1_1_U413(
    .din0(tmp_i_fu_693_p2),
    .din1(tmp_i_fu_693_p4),
    .din2(tmp_i_fu_693_p6),
    .def(tmp_i_fu_693_p7),
    .sel(tmp_i_fu_693_p8),
    .dout(tmp_i_fu_693_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state3) & (ap_enable_reg_pp0_iter0 == 1'b0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        counter_loc_1_i_i_fu_168 <= counter_loc_0_i_i;
    end else if (((icmp_ln981_reg_775 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_sof_phi_fu_256_p4 == 1'd1))) begin
        counter_loc_1_i_i_fu_168 <= add_ln1005_fu_324_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_164 <= 9'd0;
    end else if (((icmp_ln981_fu_296_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        j_fu_164 <= j_2_fu_301_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln981_reg_775_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        phi_ln1036_reg_264 <= trunc_ln1008_fu_716_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_ln1036_reg_264 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln981_reg_775_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sof_reg_251 <= 1'd0;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_reg_251 <= sof_i;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln1020_reg_768 <= icmp_ln1020_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln981_reg_775 <= icmp_ln981_fu_296_p2;
        icmp_ln981_reg_775_pp0_iter1_reg <= icmp_ln981_reg_775;
        icmp_ln994_reg_779 <= icmp_ln994_fu_311_p2;
        icmp_ln994_reg_779_pp0_iter1_reg <= icmp_ln994_reg_779;
        tmp_i_reg_784 <= tmp_i_fu_693_p9;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln981_fu_296_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln981_reg_775_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_sof_phi_fu_256_p4 = 1'd0;
    end else begin
        ap_phi_mux_sof_phi_fu_256_p4 = sof_reg_251;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln981_reg_775 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_sof_phi_fu_256_p4 == 1'd1))) begin
        counter_ap_vld = 1'b1;
    end else begin
        counter_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        counter_loc_1_i_i_out_ap_vld = 1'b1;
    end else begin
        counter_loc_1_i_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln981_reg_775_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        m_axis_video_TDATA_blk_n = m_axis_video_TREADY;
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln981_reg_775_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axis_video_TVALID = 1'b1;
    end else begin
        m_axis_video_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln981_reg_775 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ovrlayYUV_blk_n = ovrlayYUV_empty_n;
    end else begin
        ovrlayYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln981_reg_775 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ovrlayYUV_read = 1'b1;
    end else begin
        ovrlayYUV_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        phi_ln1036_i_out_ap_vld = 1'b1;
    end else begin
        phi_ln1036_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1005_fu_324_p2 = (counter_loc_1_i_i_fu_168 + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln981_reg_775 == 1'd0) & (ovrlayYUV_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((icmp_ln981_reg_775_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign counter = (counter_loc_1_i_i_fu_168 + 16'd1);

assign counter_loc_1_i_i_out = counter_loc_1_i_i_fu_168;

assign icmp_ln1020_1_fu_484_p2 = ((colorFormat_val17 == 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln1020_fu_277_p2 = ((colorFormat_val17 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln981_fu_296_p2 = ((j_fu_164 == trunc_ln_i) ? 1'b1 : 1'b0);

assign icmp_ln994_fu_311_p2 = ((zext_ln981_fu_307_p1 == add_ln994_i) ? 1'b1 : 1'b0);

assign j_2_fu_301_p2 = (j_fu_164 + 9'd1);

assign m_axis_video_TDATA = tmp_i_reg_784;

assign m_axis_video_TDEST = 1'd0;

assign m_axis_video_TID = 1'd0;

assign m_axis_video_TKEEP = 12'd4095;

assign m_axis_video_TLAST = icmp_ln994_reg_779_pp0_iter1_reg;

assign m_axis_video_TSTRB = 12'd4095;

assign m_axis_video_TUSER = sof_reg_251;

assign phi_ln1036_i_out = phi_ln1036_reg_264;

assign pix_422_10_fu_425_p4 = {{ovrlayYUV_dout[79:72]}};

assign pix_422_11_fu_445_p4 = {{ovrlayYUV_dout[95:88]}};

assign pix_422_7_fu_365_p4 = {{ovrlayYUV_dout[31:24]}};

assign pix_444_fu_341_p1 = ovrlayYUV_dout[7:0];

assign pix_rgb_12_fu_345_p4 = {{ovrlayYUV_dout[15:8]}};

assign pix_rgb_13_fu_375_p4 = {{ovrlayYUV_dout[39:32]}};

assign pix_rgb_3_fu_489_p3 = ((icmp_ln1020_1_fu_484_p2[0:0] == 1'b1) ? pix_422_7_fu_365_p4 : pix_rgb_13_fu_375_p4);

assign pix_rgb_fu_355_p4 = {{ovrlayYUV_dout[23:16]}};

assign select_ln1020_1_fu_462_p3 = ((icmp_ln1020_reg_768[0:0] == 1'b1) ? pix_rgb_fu_355_p4 : pix_rgb_12_fu_345_p4);

assign select_ln1020_fu_455_p3 = ((icmp_ln1020_reg_768[0:0] == 1'b1) ? pix_rgb_12_fu_345_p4 : pix_444_fu_341_p1);

assign tmp_174_i_i_fu_469_p4 = {{ovrlayYUV_dout[23:16]}};

assign tmp_174_i_i_fu_469_p5 = {{ovrlayYUV_dout[31:24]}};

assign tmp_176_i_i_fu_497_p2 = {{ovrlayYUV_dout[47:40]}};

assign tmp_176_i_i_fu_497_p4 = {{ovrlayYUV_dout[39:32]}};

assign tmp_176_i_i_fu_497_p5 = {{ovrlayYUV_dout[55:48]}};

assign tmp_177_i_i_fu_512_p2 = {{ovrlayYUV_dout[31:24]}};

assign tmp_177_i_i_fu_512_p4 = {{ovrlayYUV_dout[47:40]}};

assign tmp_177_i_i_fu_512_p5 = {{ovrlayYUV_dout[63:56]}};

assign tmp_178_i_i_fu_527_p2 = {{ovrlayYUV_dout[63:56]}};

assign tmp_178_i_i_fu_527_p4 = {{ovrlayYUV_dout[55:48]}};

assign tmp_178_i_i_fu_527_p5 = {{ovrlayYUV_dout[79:72]}};

assign tmp_179_i_i_fu_542_p2 = {{ovrlayYUV_dout[71:64]}};

assign tmp_179_i_i_fu_542_p4 = {{ovrlayYUV_dout[63:56]}};

assign tmp_179_i_i_fu_542_p5 = {{ovrlayYUV_dout[87:80]}};

assign tmp_180_i_i_fu_557_p2 = {{ovrlayYUV_dout[55:48]}};

assign tmp_180_i_i_fu_557_p4 = {{ovrlayYUV_dout[71:64]}};

assign tmp_180_i_i_fu_557_p5 = {{ovrlayYUV_dout[95:88]}};

assign tmp_181_i_i_fu_572_p2 = {{ovrlayYUV_dout[87:80]}};

assign tmp_181_i_i_fu_572_p4 = {{ovrlayYUV_dout[79:72]}};

assign tmp_181_i_i_fu_572_p5 = {{ovrlayYUV_dout[71:64]}};

assign tmp_182_i_i_fu_587_p2 = {{ovrlayYUV_dout[95:88]}};

assign tmp_182_i_i_fu_587_p4 = {{ovrlayYUV_dout[87:80]}};

assign tmp_182_i_i_fu_587_p5 = {{ovrlayYUV_dout[47:40]}};

assign tmp_i_fu_693_p2 = {{{{{{{{{{{{pix_422_10_fu_425_p4}, {tmp_182_i_i_fu_587_p7}}, {tmp_181_i_i_fu_572_p7}}, {tmp_180_i_i_fu_557_p7}}, {tmp_179_i_i_fu_542_p7}}, {tmp_178_i_i_fu_527_p7}}, {tmp_177_i_i_fu_512_p7}}, {tmp_176_i_i_fu_497_p7}}, {pix_rgb_3_fu_489_p3}}, {tmp_174_i_i_fu_469_p7}}, {select_ln1020_1_fu_462_p3}}, {select_ln1020_fu_455_p3}};

assign tmp_i_fu_693_p4 = {{{{{{{{{{{{pix_422_11_fu_445_p4}, {tmp_182_i_i_fu_587_p7}}, {tmp_181_i_i_fu_572_p7}}, {tmp_180_i_i_fu_557_p7}}, {tmp_179_i_i_fu_542_p7}}, {tmp_178_i_i_fu_527_p7}}, {tmp_177_i_i_fu_512_p7}}, {tmp_176_i_i_fu_497_p7}}, {pix_rgb_3_fu_489_p3}}, {tmp_174_i_i_fu_469_p7}}, {select_ln1020_1_fu_462_p3}}, {select_ln1020_fu_455_p3}};

assign tmp_i_fu_693_p6 = {{{{{{{{{{{{pix_rgb_fu_355_p4}, {tmp_182_i_i_fu_587_p7}}, {tmp_181_i_i_fu_572_p7}}, {tmp_180_i_i_fu_557_p7}}, {tmp_179_i_i_fu_542_p7}}, {tmp_178_i_i_fu_527_p7}}, {tmp_177_i_i_fu_512_p7}}, {tmp_176_i_i_fu_497_p7}}, {pix_rgb_3_fu_489_p3}}, {tmp_174_i_i_fu_469_p7}}, {select_ln1020_1_fu_462_p3}}, {select_ln1020_fu_455_p3}};

assign tmp_i_fu_693_p7 = 'bx;

assign tmp_i_fu_693_p8 = {{icmp_ln1020_reg_768}, {icmp_ln1020_1_fu_484_p2}};

assign trunc_ln1008_fu_716_p1 = counter_loc_1_i_i_fu_168[0:0];

assign zext_ln981_fu_307_p1 = j_fu_164;

endmodule //hdmi_tx_bd_v_tpg_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2
