domain_path: C:\AMDDesignTools\FPGA_PDS\FPGA_PDS\platform1\export\platform1\sw\standalone_microblaze_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
